googleapis/api-linter

- cmd/api-linter/protoc_parser.go
- go.mod
- go.sum
- lint/linter.go
- lint/linter_test.go
- lint/request.go
- lint/response.go
- lint/source.go
- lint/source_test.go
- rules/check_field_names_use_lower_snake_case.go
- rules/check_proto_syntax_version.go
- rules/corp/proto_files_must_include_version.go
- rules/corp/proto_files_must_include_version_test.go
- rules/descriptor/callback_rule.go
- rules/descriptor/callbacks.go
- rules/descriptor/callbacks_test.go
- rules/descriptor/walk.go
- rules/descriptor/walk_test.go
- rules/testutil/testutil.go
Updated Golang protobuf v2 import path to [google.golang.org/protobuf](https://godoc.org/google.golang.org/protobuf), which will be the final path.
> Updated import paths for protobuf v2.

- lint/config.go
- lint/config_test.go
- lint/linter.go
GetRuleConfig tells us which rules we actually want to run. By exposing this API, clients may be able to completely eliminate the need to compile protos by checking file paths against their set of rules.
> Exposing Configs.GetRuleConfig

- lint/config.go
- lint/linter.go
- lint/linter_test.go
This will prevent a panic inside a rule from impacting the rest of the linter rules.
> Executing rules inside a function that recovers from panics.

- .circleci/config.yml
This adds the `google/protobuf/` protos in the place where
protoc looks for them, allowing them to be imported in tests.
> [chore] Install stdlib protos in test environment.

- lint/registry_test.go
- rules/0131_test.go
- rules/0132_test.go
- rules/check_field_names_use_lower_snake_case_test.go
- rules/check_proto_syntax_version_test.go
- rules/rules_test.go
- testutil/testutil.go
- testutil/testutil_test.go
As described in #99, currently, if anything in `testutil.MustXxx` fails, the entire test suite will stop executing because it uses `log.Fatalf`. By passing in `t` and using `t.Fatalf`, we will only fail the current test if a `MustXxx` function fails. We should follow this pattern with all `testutil.MustXxx` functions moving forward, as they are only supposed to be used in tests, so `t` should always be available.
> Using testing.T.Fatalf instead of log.Fatalf

- lint/linter_test.go
`proto.String` is not yet synced to google3's version of protobuf/proto, so we're instead manually creating the `*string` for the filename.
> Removed usage of function that's not available in google3

- lint/source.go
- rules/descriptor/callback_rule.go
Also added a helper function to return the start location if a descriptor is not found, as this is the behavior that most rules want to use.
> Fixed bug in DescriptorLocation if d is nil

- lint/request.go
- lint/source.go
This is the first step to remove dependency on `FileDescriptorProto` in the `lint` package. In other words, the linter will expect a _resolved_ FileDescriptor that has source locations.
> Extract DescriptorSource from FileDescriptor.SourceLocations.

- rules/0132.go
When I ran the linter, the AIP-132 rule for List* RPCs having a parent field in the input message was emitted. I felt that the message didn't make a lot of sense 
>method "ListProductsInProductSet" has no `parent` field
A method doesn't have fields and maybe it could be referring to the output message.
This PR makes the message more explicit/actionable by including the offending input message name.
> [aip-132] make missing parent message more descriptive

- .github/renovate.json
- renovate.json
Renovate is _really_ spammy for constantly-updated Go modules,
which is annoying.
Reconfigure it to keep one PR with dependency updates which we
can merge occasionally.
> [chore] Renovate should stick to a single PR for updates.

- lint/lint.go
- lint/lint_test.go
- lint/rule.go
- lint/rule_registry.go
- lint/rule_test.go
Nothing outside of lint package should depend on it so that we can change it more easily.
> Made protoRule interface private.

- lint/rule.go
- lint/rule_test.go
- rules/aip0131/message_rules.go
- rules/aip0131/message_rules_test.go
- rules/aip0131/method_rules.go
- rules/aip0131/method_rules_test.go
- rules/aip0132/message_rules.go
- rules/aip0132/message_rules_test.go
- rules/aip0132/method_rules.go
- rules/aip0132/method_rules_test.go
There is a really common pattern which looks like...
```go
// Sanity check: Is this a descriptor that this actually
// cares about.
if !relevantMessage(message) {
return nil
}
```
This formalizes that into an (optional) `OnlyIf` function that
restricts a rule to a scope.
> [feat] Add OnlyIf to rules.

- lint/rule_name.go
- lint/rule_name_test.go
We should enforce a stricter standard on rule names.
- They should always be lower-case (no upper-case).
- They should always start with a letter or number.
- They should always use `-` as a word separator, not `_` (kebab-case).
- They should not begin or end with a word separator.
This PR does all of that with the exception of enforcing no
trailing hyphens (I am willing to assume that given the enforcement
of the remaining rules, nobody will try that).
> [fix] Be stricter about rule names.

- lint/lint.go
- lint/lint_test.go
- lint/rule.go
- lint/rule_registry.go
- lint/rule_test.go
This undoes #162, for the following reasons:
1. It is an anti-pattern for a public function to return a private interface.
2. In my upcoming PR (edit: #209) for the rules for #167, I have a need to declare a struct in a rule test with a `lint.ProtoRule` as one of the values, which I can not do if it is private.
3. The entire point of going to an interface is to be able to use that interface. :)
> [chore] Export lint.ProtoRule

- rules/internal/testutils/parse.go
- rules/internal/testutils/parse_test.go
This adds a `testutils.ParseProto3String` and `testutils.ParseProto3Tmpl` method, to make it easier to parse protobuf string templates in tests, and keep the focus on what is being tested.
Each method adds `syntax = "proto3";` to the top (we basically only work in proto3 so it is silly to boilerplate it over and over) and the template method also parses out a template.
> [feat] Add helper method for proto3 templates.

- rules/aip0134/message_rules.go
It checks for two required fields, not just the name field.
> [AIP-134] Rename one rule.

- lint/rule.go
- lint/rule_test.go
- rules/aip0192/aip0192.go
- rules/aip0192/aip0192_test.go
- rules/aip0192/leading_comments.go
- rules/aip0192/leading_comments_test.go
- rules/rules.go
Also adds a `DescriptorRule` that pokes everything.
I will migrate the AIP-140 abbreviations component to that
after this is merged.
Fixes #174.
> [AIP-192] Add rule for leading comments.

- rules/aip0141/types.go
- rules/internal/utils/type_name.go
- rules/internal/utils/type_name_test.go
I have now needed several times a way to get the string type
for a scalar (e.g. "string", "int32", etc.). Time to make it a
utility function.
> [feat] Add GetScalarTypeName function.

- rules/aip0142/aip0142.go
- rules/aip0142/timestamp.go
- rules/aip0142/timestamp_test.go
- rules/internal/utils/type_name.go
- rules/internal/utils/type_name_test.go
I believe this is the last rule needed for standard fields.
Fixes #183.
> [AIP-142] Add field type checks for timestamps.

- rules/aip0131/method_rules.go
- rules/aip0133/method_rules.go
- rules/aip0134/method_rules.go
- rules/aip0135/method_rules.go
- rules/internal/utils/http.go
- rules/internal/utils/http_test.go
In writing an upcoming rule for AIP-156, I realized I have cases
where I *only* care about the URI, and not the method. Getting
this is a huge pain.
I have therefore refactored `GetHTTPRules` to return a custom
struct instead of the underlying proto annotation. The custom
struct has `Method` and `URI` fields that correspond to the
values on the annotation.
In the refactor to the standard method rules, the change clearly
does a better job of expressing intent: `if r.Method == "POST"`
is much clearer than `if r.GetPost() != ""`.
> Refactor GetHTTPRules.

- rules/aip0126/unspecified.go
- rules/aip0131/aip0131.go
- rules/aip0131/method_rules.go
- rules/aip0131/method_rules_test.go
- rules/aip0133/aip0133.go
- rules/aip0133/method_rules.go
- rules/aip0133/method_rules_test.go
- rules/aip0134/aip0134.go
- rules/aip0134/method_rules.go
- rules/aip0134/method_rules_test.go
- rules/aip0135/aip0135.go
- rules/aip0135/method_rules.go
- rules/aip0135/method_rules_test.go
- rules/aip0136/aip0136.go
- rules/aip0136/aip0136_test.go
- rules/aip0136/http_method.go
- rules/aip0136/http_method_test.go
- rules/aip0136/prepositions.go
- rules/aip0136/prepositions_test.go
- rules/aip0136/verb_noun.go
- rules/aip0136/verb_noun_test.go
- rules/internal/data/data.go
- rules/internal/data/data_test.go
- rules/rules.go
This also renames `http-verb` in other AIPs to `http-method`, which is the term most folks use.
Uses #247 as a base, because I made a mistake.
> [AIP-136] Add initial rules for AIP-136.

- docs/_config.yml
- docs/_includes/linter-breadcrumb.html
- docs/_includes/linter-nav-mobile.html
- docs/_includes/linter-rule-listing.html
- docs/_layouts/default.html
Because we host from a subdirectory, all of the links that worked
on the development site do not work on live.
This adds a `<base href=...>` and moves to relative individual
links, which should work.
> [fix] Address broken links.

- cmd/api-linter/main.go
This allows injecting Google internal configs, for example, we can create a `google_configs.go` file with:
```golang
package main
func init() {
globalConfigs = append(globalConfigs, myConfigs...)
}
```
> Allowed injecting configs.

- cmd/api-linter/cli.go
- docs/index.md
A user can specify a list of file descriptor sets for searching imports, which matches the behavior of `protoc`.
> Allow a delimited list of descriptor sets.

- lint/problem.go
- lint/problem_test.go
Example output:
```yaml
- file_path: dummy.proto
problems:
- message: Method "GetDummyRequest" has no `name` field
location:
start_position:
line_number: 5
column_number: 1
end_position:
line_number: 7
column_number: 2
rule_id: core::0131::request-name-field
rule_doc_uri: https://googleapis.github.io/api-linter/rules/core/0131-request-name-field.html
```
> Added rule doc uri to the output.

- cmd/api-linter/cli.go
- cmd/api-linter/cli_test.go
- cmd/api-linter/integration_test.go
- go.mod
- go.sum
```
Usage of api-linter:
--config string                 The linter config file.
--disable-rule stringArray      Disable a rule with the given name.
May be specified multiple times.
--enable-rule stringArray       Enable a rule with the given name.
May be specified multiple times.
--output-format string          The format of the linting results.
Supported formats include "yaml", "json" and "summary" table.
YAML is the default.
-o, --output-path string            The output file path.
If not given, the linting results will be printed out to STDOUT.
--proto-descriptor-set string   A delimited (':') list of files each containing a FileDescriptorSet for searching proto imports.
-I, --proto-path stringArray        The folder for searching proto imports.
May be specified multiple times; …
```
> Used pflag.

- lint/problem.go
- locations/descriptor_locations.go
- locations/descriptor_locations_test.go
- locations/field_locations.go
- locations/field_locations_test.go
- locations/file_locations.go
- locations/file_locations_test.go
- locations/locations.go
- locations/locations_test.go
- locations/method_locations.go
- locations/method_locations_test.go
- rules/aip0126/unspecified.go
- rules/aip0126/upper_snake_values.go
- rules/aip0131/synonyms.go
- rules/aip0133/request_resource_field.go
- rules/aip0133/synonyms.go
- rules/aip0134/request_resource_field.go
- rules/aip0134/synonyms.go
- rules/aip0136/prepositions.go
- rules/aip0136/verb_noun.go
- rules/aip0140/abbreviations.go
- rules/aip0140/prepositions.go
- rules/aip0141/count_suffix.go
- rules/aip0142/time_field_names.go
- rules/aip0143/standardized_codes.go
- rules/aip0191/syntax.go
- rules/aip0192/has_comments.go
This creates a Go package for `locations` to group these helper
functions together. It also adds several more:
- FieldType
- MethodRequestType
- MethodResponseType
This will better group these functions together in godoc, which
will be useful to rule authors.
Conveniently, also fixes #306.
> [refactor] Move location functions into their own package.

- cmd/api-linter/cli.go
This allows us to add more format functions in Google3, and it is easier to maintain those functions.
> Refactor output format.

- cmd/api-linter/cli.go
It is using `protoparse.ResolveFilenaming` to resolve absolute file paths (e.g., "./test.proto") into relative ones (e.g., "test.proto") before feeding the proto files into `protoparse`.
I verified:
```
git clone git@github.com:googleapis/googleapis.git ~/Downloads/googleapis
api-linter -I ~/Downloads/googleapis --output-format summary $(find ~/Downloads/googleapis -name '*.proto')
```
and got:
```
+--------------------------------------------+------------------+----------------+
|                    RULE                    | TOTAL VIOLATIONS | VIOLATED FILES |
+--------------------------------------------+------------------+----------------+
| core::0131::http-body                      |                1 |              1 |
| core::0131::http-method                    |                1 | …
```
> Resolved proto file paths.

- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
- cmd/api-linter/internal/testdata/build_errors.proto
Fixes #314.
Feel free to commandeer this, first time contributing to this repository so not sure if this is how you want tests written etc. This also just combines the errors into a string and prints them out, nothing too fancy here. However it works:
```
$ api-linter cmd/api-linter/internal/testdata/build_errors.proto
2019/11/08 13:17:24 cmd/api-linter/internal/testdata/build_errors.proto:8:1: syntax error: unexpected '}', expecting ';' or '['
cmd/api-linter/internal/testdata/build_errors.proto:13:1: syntax error: unexpected '}', expecting ';' or '['
```
> Print multiple build errors

- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
- cmd/api-linter/main.go
- docs/configuration.md
- lint/config.go
- lint/config_test.go
- lint/lint.go
- lint/lint_test.go
The configurations work in two steps:
First, we check if a configuration is matched against the given path.
1. If none is matched, the rule is enabled by default;
2. Otherwise, we apply the matched configuration against the rule:
(a) if the given rule is in the disabled list, the rule is disabled;
(b) if the given rule is in the enabled list, the rule is enabled;
(c) if the given rule is in neither list, the rule remains the state determined by the previous matched configuration.
> Rewrite lint configuration.

- go.mod
Go 1.13 supports [errors wrapping](https://golang.org/doc/go1.13#error_wrapping).
> Update Go to v1.13

- locations/descriptor_locations.go
- locations/field_locations.go
- locations/file_locations.go
- locations/file_locations_test.go
- locations/locations.go
- locations/method_locations.go
This refactors `locations.pathLocation` to take the baseline
descriptor and the path suffix. This significantly reduces
the amount of work being done in the public methods in the
package.
> [refactor] Make locations.pathLocation better.

- docs/rules/0191/file-option-consistency.md
- rules/aip0191/aip0191.go
- rules/aip0191/file_option_consistency.go
- rules/aip0191/file_option_consistency_test.go
This rule checks that options like `csharp_namespace`, `ruby_package`,
and so on are applied consistently throughout an API.
~Uses #365 as a base (for `hasPackage`).~
> [AIP-191] File option consistency.

- docs/rules/0191/csharp-namespace.md
- docs/rules/0191/php-namespace.md
- docs/rules/0191/ruby-package.md
This downgrades from **should** to **may** as @bufdev suggested (and I am convinced he is right).
> [docs] Permit, rather than recommend, disabling the AIP-191 rules.

- lint/rule.go
- lint/rule_test.go
- rules/aip0126/unspecified.go
We would like to ensure that a rule checks only the descriptor as provided; in other words, a rule should not return a problem about other descriptors. It makes a rule much easy to understand and for future refactoring. 
For example, we would like to remove `Descriptor` in the `Problem`, as we already know which `Descriptor` a rule is checking and therefore it is redundant to ask the rule developer to return it again in a problem.
> [Refactor] Unspecified: should check the enum value.

- rules/aip0203/immutable.go
- rules/aip0203/input_only.go
- rules/aip0203/optional.go
- rules/aip0203/output_only.go
- rules/aip0203/required.go
- rules/internal/utils/extension.go
- rules/internal/utils/extension_test.go
Instead of returning a slice of the obnoxious-to-use enum
annotation, we return a stringset instead. (Yay, `Contains`!)
> [refactor] Make utils.GetFieldBehavior better.

- rules/internal/testutils/parse.go
This will make templates able to parse things like quotes and such.
I somehow did not find this when writing the original parse
implementation.
> [refactor] Use text/template, not html/template.

- docs/rules/0214/index.md
- docs/rules/0214/resource-expiry.md
- rules/aip0214/aip0214.go
- rules/aip0214/aip0214_test.go
- rules/aip0214/resource_expiry.go
- rules/aip0214/resource_expiry_test.go
- rules/internal/testutils/parse.go
- rules/rules.go
> [AIP-214] Enforce `ttl` field presence.

- docs/rules/0140/prepositions.md
- docs/rules/0140/reserved-words.md
- rules/aip0140/aip0140.go
- rules/aip0140/reserved_words.go
- rules/aip0140/reserved_words_test.go
This rule currently checks Java, JavaScript, and Python 3.
I will add a couple additional languages in a follow-up PR.
> [AIP-140] Prohibit reserved words.

- rules/aip0132/request_field_types.go
- rules/aip0141/forbidden_types.go
- rules/aip0142/time_field_names.go
- rules/aip0142/time_field_type.go
- rules/aip0143/string_type.go
- rules/aip0217/unreachable_field_type.go
- rules/internal/utils/type_name.go
- rules/internal/utils/type_name_test.go
Having different methods is duplicative. One is better.
> [refactor] Improve utils.GetTypeName

- docs/rules/0122/name-suffix.md
This changes the heading from "HTTP URI Case" to "Name field suffix".
> Fix copy-pasted heading in name-suffix.

- docs/index.md
Due to some differences about protobuf dependencies, we have an internal, compiled version in Google. In other words, the Github version installed using `go get` does not work in Google3. In this PR, we advice googlers to use the internal, released binary instead.
> Add a installation note to Googlers.

- rules/aip0191/java_outer_classname.go
- rules/aip0191/java_outer_classname_test.go
- rules/internal/testutils/parse.go
- rules/internal/testutils/parse_test.go
Previously it was taking the directory into account
when determining the `java_outer_classname` value,
which was wrong.
> [fix] Make java_outer_classname ignore directories.

- lint/rule.go
- lint/rule_test.go
This PR changes from "disable on descriptor or file" to
"disable on descriptor or any parent, including file".
Fixes #406.
> [feat] Allow disabling rules to cascade.

- docs/rules/0134/request-unknown-fields.md
Fairly straight forward typo fix; makes spellcheckers happy. 🙂
> fix typo in not-precedent comment: reaosns -> reasons

- docs/rules/0216/nesting.md
Looks like a copy/paste mistake, should be core::0216::nesting
> Fix a typo in the disabling logic for core::0216

- docs/rules/0142/time-field-names.md
> Fix typo in core::0142 disabling command

- docs/rules/0136/http-parent-variable.md
- docs/rules/0136/http-uri-suffix.md
- rules/aip0136/aip0136.go
- rules/aip0136/http_parent_variable.go
- rules/aip0136/http_parent_variable_test.go
- rules/aip0136/http_uri_suffix.go
The AIP-136 [http-uri-suffix](https://linter.aip.dev/136/http-uri-suffix) rule continues to be the single most confusing for people. The false positive rate is basically zero, but the problems it finds are varied and subtle and so the error message is useless a lot of the time.
This adds a new rule, http-parent-variable, for catching a common case that _looks_ like a false positive (but is not) and quiets the http-uri-suffix rule if the other rule is noisy.
> [AIP-136] Enforce parent variable consistency.

- docs/rules/0203/immutable.md
- docs/rules/0203/input-only.md
- docs/rules/0203/optional-conflict.md
- docs/rules/0203/optional-consistency.md
- docs/rules/0203/optional.md
- docs/rules/0203/output-only.md
* Add =disabled to 0203/immutable.md instructions
* Add =disabled to 0203/input-only.md instructions
* Add =disabled to 0203/optional-conflict.md
* Add =disabled to 0203/optional-consistency.md instructions
* Add =disabled to 0203/optional.md instructions
* Add =disabled to 0203/output-only.md instructions
> Include `=disabled` in various AIP 203 instructions (#1)

- rules/aip0192/no_html.go
- rules/aip0192/no_html_test.go
This builds off of @msuozzo's idea to check for closing tags (see #501) but adds some extra tests and clean up.
> Fix #500 - Check for closing HTML tags via regex.

- lint/rule.go
- lint/rule_test.go
@wora had a really good point: running lint rules on deprecated
descriptors almost never makes sense, and they contribute to noise
for API producers.
This PR issues a blanket disable on any descriptor with a
`deprecated=true` annotation.
> [feat] Ignore deprecated descriptors.

- cmd/api-linter/integration_test.go
- lint/lint.go
- lint/rule.go
- lint/rule_test.go
This fixes an issue where the linter does not respect a disable comment
on "package" statements, which themselves do not have an associated
Descriptor (natural file location). Instead these lint rules can specify
a Location, and this location will now be respected when checking for
rule disable comments.
> Support source code location overrides for ruleEnabled.

- docs/rules/0191/file-layout.md
https://aip.dev/191#file-layout says enum defs should be at the end so we should not complain if they are after messages.
> Fix a logical typo: below -> above

- rules/aip0123/aip0123.go
- rules/aip0123/resource_annotation_test.go
In Cloud KMS, we echo the name of the resource used for cryptographic
operations in response messages, so that callers can verify that the
correct resource was used.
(Corruption of a single bit in the `name` field of a request message
could end up with the wrong key being used. We'd like for a caller to be
able to detect when that's happened.)
> Don't enforce AIP-0123 on Response messages

- rules/aip0136/http_uri_suffix.go
- rules/aip0136/http_uri_suffix_test.go
The lint rule contradicts [AIP-136](https://aip.dev/136) on the SortBooks example.
This fixes that.
> [AIP-136] Be more permissive on collection suffixes.

- cmd/api-linter/cli.go
- cmd/api-linter/cli_test.go
- cmd/api-linter/integration_test.go
- cmd/api-linter/main.go
This change introduces a new flag `--set-exit-status` which will return
a non-zero exit status when lint problems are found. This is a non
breaking change that allows api-linter to be used in CI environments.
This addresses issue #522
> [feat] return non-zero exit status when lint problems found

- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
This PR fixes a false positive reading of the lint results by checking `result[*].Problems` for lint results per file
see https://github.com/googleapis/api-linter/pull/534#discussion_r416489984
> fix detection of lint problems for exit status

- rules/aip0191/php_namespace.go
- rules/aip0191/php_namespace_test.go
Suggested backslashes were being doubled by fmt.Sprintf escaping added by %q. Unit tests also verified data with %q, so the incorrect expected values were not readily apparent.
> Fix php_namespace linter suggestions with extra backslashes.

- .github/renovate.json
- .github/renovate.json5
Ignore `go-pluralize`, which has been broken for a month, and `genproto`, which is just irritating.
Also convert to JSON5, which Renovate supports, so we can have comments.
> [chore] Fix Renovate updates.

- rules/aip0136/http_uri_suffix_test.go
This was already fixed, but add a test.
Fixes #532.
> [AIP-136] suffix: add test for no parent

- rules/aip0136/http_parent_variable_test.go
Ensure that there is no false positive on the rule that
requires the parent variable to match the method name.
> [AIP-136] Add batch method tests.

- rules/aip0132/request_parent_required.go
- rules/aip0132/request_parent_required_test.go
- rules/aip0133/request_parent_required.go
- rules/aip0133/request_parent_required_test.go
- rules/internal/utils/extension.go
- rules/internal/utils/extension_test.go
- rules/internal/utils/type_name.go
Fixes #483.
This permits top level fields on List or Create requests
where the corresponding resource is annotated with
google.api.resource and has only one variable.
This implementation is intentionally cautious, preferring
to still complain unless it is sure that a top-level resource
is in use.
> [AIP-132/133] Permit no parent on top level fields.

- go.mod
- go.sum
0.1.4 seems not to exist. Not sure how we bumped to it, or anything passed. Weird.
> [chore] Move go-pluralize back to 0.1.1

- docs/rules/0191/java-outer-classname.md
The docs do not reflect the change made in #540.
> [docs] Fix docs for java-outer-classname.

- docs/rules/0146/any.md
- docs/rules/0146/index.md
- rules/aip0146/aip0146.go
- rules/aip0146/aip0146_test.go
- rules/aip0146/any.go
- rules/aip0146/any_test.go
- rules/aip0215/versioned_packages.go
- rules/internal/utils/common_proto.go
- rules/internal/utils/common_proto_test.go
- rules/rules.go
Note: Do not merge this until AIP-146 itself is merged.
This also refactors the common proto check in AIP-215 into a
utility function so it can be reused here.
> [AIP-146] Discourage Any.

- docs/rules/0216/value-synonyms.md
- rules/aip0216/aip0216.go
- rules/aip0216/value_synonyms.go
- rules/aip0216/value_synonyms_test.go
This rule catches common State mistakes like `SUCCESSFUL` and
`SUCCESS` and corrects them.
It also catches `CANCELED` and asks for the two-L spelling:
`CANCELLED`. Both are correct, but we should use one consistently
and the AIP uses the two-L version.
> [AIP-216] Add lint rule for common state value synonyms.

- .github/workflows/release.yaml
- README.md
- cmd/api-linter/cli.go
- cmd/api-linter/version.go
This sets up CI/CD for binary releases when we make release tags.
Fixes #53.
> chore: Binary releases.

- lint/rule.go
> docs: Linter can only report errors in the running file.

- rules/aip0136/http_parent_variable.go
- rules/aip0136/http_parent_variable_test.go
plural is not currently converted to snake_case, but is used in comparison on line 46
> Fix snake_case for plural resource name

- rules/aip0140/prepositions.go
- rules/aip0140/prepositions_test.go
It makes no sense to flag on this because we called the message `google.type.DayOfWeek`.
> fix: Permit `hour_of_day` and `day_of_week`.

- rules/aip0140/abbreviations.go
- rules/aip0140/abbreviations_test.go
> fix: AIP-140 – Permit abbreviated-words as prefixes.

- .github/release-tool/changelog.go
- .github/release-tool/main.go
- .github/release-tool/version.go
- .github/workflows/release.yaml
This makes us auto-release every Wednesday at 20:00 UTC (noon Pacific when in standard time), and is tolerant of weeks with no changes.
You can see the testing/thrashing in GitHub Actions. As in #567, I cleaned up after myself.
> chore: Add release-on-a-schedule.

- .github/renovate.json5
The author fixed the issue that forced us to peg to v0.1.1.
Once this is merged, Renovate will send update PRs for it again.
> chore: Update go-pluralize again.

- go.mod
- go.sum
- lint/config.go
Closes #588. (Renovate was not able to automate this one.)
> chore: Update module bmatcuk/doublestar to v2.0.0.

- docs/rules/0122/resource-reference-type.md
- rules/aip0122/aip0122.go
- rules/aip0122/resource_reference_type.go
- rules/aip0122/resource_reference_type_test.go
> feat: Resource references should be strings.

- rules/aip0140/base64.go
- rules/aip0140/base64_test.go
Add missing string format parameter. The error is showing as:
"Field %q mentions base64 encoding in comments, so it should probably be type `bytes`, not `string`"
> Fix missing field name in core_0140_base6 rule.

- rules/aip0136/http_uri_suffix.go
- rules/aip0231/aip0231.go
- rules/aip0231/request_parent_field.go
- rules/aip0231/request_parent_field_test.go
- rules/aip0233/request_parent_field.go
- rules/aip0233/request_parent_field_test.go
- rules/aip0234/request_parent_field.go
- rules/aip0234/request_parent_field_test.go
Also, I rewrote the tests for these rules from scratch, as they
were in a weird state.
Fixes #615.
> fix: Permit top-level resources to have batch methods.

- docs/rules/0235/http-body.md
- docs/rules/0235/http-method.md
- docs/rules/0235/index.md
- docs/rules/0235/request-message-name.md
- rules/aip0235/aip0235.go
- rules/aip0235/aip0235_test.go
- rules/aip0235/http_body.go
- rules/aip0235/http_body_test.go
- rules/aip0235/http_method.go
- rules/aip0235/http_method_test.go
- rules/aip0235/request_message_name.go
- rules/aip0235/request_message_name_test.go
- rules/rules.go
These are adapted from AIP-135 and AIP-231.
We still need lints for the following, and possibly others, for #612:
- request URI
- request message resource reference
- request message unknown fields
- response message
> feat: Add initial rules for AIP-235.

- rules/aip0231/request_parent_field.go
- rules/aip0231/request_parent_field_test.go
- rules/aip0233/request_parent_field.go
- rules/aip0233/request_parent_field_test.go
- rules/aip0234/request_parent_field.go
- rules/aip0234/request_parent_field_test.go
Batch URIs reference a collection, not an individual resource, so a parent field should be required when there is at least one resource in the URI.
The parent field should be absent when there are no resources in the URI, but these rules don't yet enforce that.
#615
> Fix erroneous logic for batch request-parent-field rules

- docs/rules/0231/request-names-behavior.md
- docs/rules/0231/request-names-reference.md
- docs/rules/0235/request-names-behavior.md
- docs/rules/0235/request-names-reference.md
- rules/aip0231/aip0231.go
- rules/aip0231/request_names_behavior.go
- rules/aip0231/request_names_behavior_test.go
- rules/aip0231/request_names_reference.go
- rules/aip0231/request_names_reference_test.go
- rules/aip0235/aip0235.go
- rules/aip0235/request_names_behavior.go
- rules/aip0235/request_names_behavior_test.go
- rules/aip0235/request_names_reference.go
- rules/aip0235/request_names_reference_test.go
These annotations were added in https://github.com/aip-dev/google.aip.dev/pull/612.
Part of #612.
> Add rules for batch-request names-field annotations

- rules/aip0136/http_uri_suffix.go
- rules/aip0136/http_uri_suffix_test.go
Another tweak to the perpetually-difficult `http-uri-suffix` rule from AIP-136.
Fixes #622.
> fix: Permit two-word top-level collections in the URI suffix.

- rules/internal/utils/declarative_friendly.go
- rules/internal/utils/declarative_friendly_test.go
Otherwise they can not be sent to `OnlyIf`.
Additionally, support request messages (e.g. `CreateBookRequest`).
> refactor: Make separate IsDeclarativeFriendly methods for message and method.

- docs/rules/0134/request-allow-missing-field.md
- docs/rules/0134/request-unknown-fields.md
- rules/aip0134/aip0134.go
- rules/aip0134/request_allow_missing_field.go
- rules/aip0134/request_allow_missing_field_test.go
- rules/aip0134/request_unknown_fields.go
Note: This rule applies to declarative-friendly resources only.
> feat: Add `allow_missing` rule to AIP-134.

- docs/rules/0154/declarative-friendly-required.md
- docs/rules/0154/field-type.md
- docs/rules/0154/index.md
- docs/rules/0154/no-duplicate-etag.md
- rules/aip0154/aip0154.go
- rules/aip0154/aip0154_test.go
- rules/aip0154/declarative_friendly_required.go
- rules/aip0154/declarative_friendly_required_test.go
- rules/aip0154/field_type.go
- rules/aip0154/field_type_test.go
- rules/aip0154/no_duplicate_etag.go
- rules/aip0154/no_duplicate_etag_test.go
- rules/internal/utils/declarative_friendly.go
- rules/internal/utils/declarative_friendly_test.go
- rules/internal/utils/find.go
- rules/internal/utils/find_test.go
- rules/rules.go
This adds three rules:
- Etags required on declarative-friendly resources
- Etags should not be duplicated on request messages that include the resource
- Etags should be strings.
> feat: Add three rules for AIP-154.

- docs/rules/0133/http-body.md
Why:
- I was violating the linter in this way and this documentation did not help me learn why.
Changed:
- Added an incorrect/correct pair that uses additional_bindings
> Add example for a violation using additional_bindings

- docs/rules/0135/request-unknown-fields.md
It's permitted at https://github.com/googleapis/api-linter/blob/005f6feace6f363c94bf559fe9845bbba964688e/rules/aip0135/request_unknown_fields.go#L35.
> Add validate_only field to AIP-163 request-unknown-fields doc

- docs/rules/0134/response-lro.md
- rules/aip0134/aip0134.go
- rules/aip0134/response_lro.go
- rules/aip0134/response_lro_test.go
> feat: Add LRO rule for Update methods (declarative-friendly).

- docs/rules/0148/declarative-friendly-fields.md
- docs/rules/0148/human-names.md
- rules/aip0148/aip0148.go
- rules/aip0148/declarative_friendly_fields.go
- rules/aip0148/declarative_friendly_fields_test.go
> feat: Add rule for required standard fields.

- rules/aip0132/request_parent_required.go
- rules/aip0132/request_parent_required_test.go
- rules/aip0231/request_parent_field.go
- rules/aip0231/request_parent_field_test.go
- rules/aip0233/request_parent_field.go
- rules/aip0233/request_parent_field_test.go
- rules/aip0234/request_parent_field.go
- rules/aip0234/request_parent_field_test.go
- rules/aip0235/request_parent_field.go
- rules/aip0235/request_parent_field_test.go
First, we revert commit 04d68971f51c68363ce75c5bf441a5c3d72b59dc: In #631 I mistakenly thought this was looking at the HTTP pattern, not the resource pattern.
Next, we fix #620.
> fix: Correct handling of top-level resources in parent-field lints

- docs/rules/0132/http-body.md
- docs/rules/0132/http-method.md
- rules/aip0132/aip0132.go
- rules/aip0132/http_body.go
- rules/aip0132/http_body_test.go
- rules/aip0132/http_method.go
- rules/aip0132/http_method_test.go
> feat: Add HTTP body and method rules for AIP-132

- docs/rules/0203/unordered-list-repeated.md
- go.mod
- go.sum
- rules/aip0203/aip0203.go
- rules/aip0203/unordered_list_repeated.go
- rules/aip0203/unordered_list_repeated_test.go
We update `go.mod` to pick up the corresponding changes to the field-behavior proto.
> feat: Add rule for UNORDERED_LIST field behavior

- docs/rules/0162/commit-request-name-field.md
- rules/aip0162/aip0162.go
- rules/aip0162/commit_request_name_field.go
- rules/aip0162/commit_request_name_field_test.go
> feat: Add rule for AIP-162 Commit request name field

- rules/aip0191/csharp_namespace.go
- rules/aip0191/csharp_namespace_test.go
> fix: Allow V1Main (version selector) in the C# namespace.

- docs/rules/0162/delete-revision-http-body.md
- docs/rules/0162/delete-revision-http-method.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_http_body.go
- rules/aip0162/delete_revision_http_body_test.go
- rules/aip0162/delete_revision_http_method.go
- rules/aip0162/delete_revision_http_method_test.go
> feat: Add rules for AIP-162 Delete Revision HTTP body and method

- rules/aip0203/aip0203.go
- rules/aip0203/immutable.go
- rules/aip0203/input_only.go
- rules/aip0203/optional.go
- rules/aip0203/optional_test.go
- rules/aip0203/output_only.go
- rules/aip0203/required.go
This commit makes those lint rules stop complaining if *both* the terms "required" and "optional" are present; this is a common occurrence when fields are conditionally required, which is a good reason to use the terms in comments without an annotation.
Fixes #759.
> fix: Make the required and optional rules less noisy.

- rules/aip0158/response_plural_first_field.go
- rules/aip0158/response_plural_first_field_test.go
> fix: Account for empty messages in AIP-158 response-plural-first-field rule

- rules/aip0132/aip0132.go
- rules/aip0132/request_parent_required_test.go
- rules/aip0132/request_unknown_fields_test.go
- rules/aip0162/aip0162.go
> fix: Suppress AIP-132 rules for AIP-162 methods and messages

- cmd/api-linter/cli.go
- cmd/api-linter/rules.go
This is to address #768.  I'm more than happy to change the implementation but my goal here is to be able to extract information about how many rules the linter validates against so we can track our progress along enabling all the rules.  Example usage is below:
```bash
./api-linter --list-rules
./api-linter --list-rules --output-format yaml
./api-linter --list-rules --output-format yml
./api-linter --list-rules --output-format json | jq '.'
./api-linter --list-rules --output-format summary
```
Right now the most interesting metric I'm interested in is thi:
```bash
./api-linter --list-rules --output-format json | jq '. | length'
282
```
In perhaps a subsequent PR I would like to start including the URL to the rule as well but that information is an internal implementation detail right now …
> feat: add new --list-rules flag to output rules database list

- docs/rules/0203/unordered-list-repeated.md
Currently, 0203/unordered-list-repeated.md has the same permalink as 0203/optional.md
As a result, https://linter.aip.dev/203/optional displays information about UNORDERED_LIST instead of about OPTIONAL, and https://linter.aip.dev/203/unordered-list-repeated is a 404.
> Fixes 0203/unordered-list-repeated links

- docs/rules/0162/list-revisions-request-no-order-by-field.md
- rules/aip0162/aip0162.go
- rules/aip0162/list_revisions_request_no_order_by_field.go
- rules/aip0162/list_revisions_request_no_order_by_field_test.go
From https://google.aip.dev/162#listing-revisions:
> Revisions **must** be ordered in reverse chronological order. An `order_by` field **should not** be provided.
Part of #721.
> feat: Add rule to suggest removing AIP-162 List Revisions request order_by fields

- docs/rules/0162/list-revisions-request-name-behavior.md
- rules/aip0162/aip0162.go
- rules/aip0162/list_revisions_request_name_behavior.go
- rules/aip0162/list_revisions_request_name_behavior_test.go
> feat: Add rule for AIP-162 List Revisions request name behavior

- docs/rules/0141/forbidden-types.md
Though it's not clear to me whether the suppression comment should be added over the field or message.
> docs: Fix typo in core::0141::forbidden-types

- rules/aip0158/aip0158.go
- rules/aip0158/request_page_size_field_test.go
- rules/aip0158/request_page_token_field_test.go
Based on an internal bug report: If a message isn't actually a request but happens to have a `page_size` field, it shouldn't be required to have a `page_token` field. An example of this is a message that itself will be serialized as a page token, e.g.
```proto
message FooPageToken {
int32 page_size = 1;
int32 page_num = 2;
}
```
This seems to have been an oversight in #496.
It is debatable whether we should apply this to the corresponding `isPaginatedResponseMessage` function, though it seems less likely to come up.
> fix: Suppress core::aip0158::request-page-token-field for non-request messages

- rules/aip0148/declarative_friendly_fields.go
- rules/aip0148/declarative_friendly_fields_test.go
- rules/aip0156/forbidden_methods.go
Fixes #791.
We can add a new rule to *prevent* singleton resources from having `delete_time` and `uid` fields in a followup PR.
> fix: Do not require delete_time or uid fields for singleton resources

- docs/rules/0152/response-message-name.md
The rule looks at the method, not the message.
> docs: Replace message with method in AIP-152

- docs/rules/0123/resource-reference-type.md
- docs/rules/0126/unspecified.md
- docs/rules/0126/upper-snake-values.md
- docs/rules/0132/request-parent-field.md
- docs/rules/0132/request-parent-required.md
- docs/rules/0132/request-show-deleted-required.md
- docs/rules/0133/request-parent-field.md
- docs/rules/0133/request-parent-required.md
- docs/rules/0140/prepositions.md
- docs/rules/0140/reserved-words.md
Specifically, this:
* Changes remaining direct links (e.g. `[AIP-NNN](https://aip.dev/NNN)`)
to the reference-style links (e.g.  `[AIP-NNN][]`)
* Updates a few existing `http` AIP links to `https`
* Fixes a couple of incorrect references in the `0140` docs
> API Linter: In the rule docs, reference AIP links in a uniform way.

- docs/rules/0203/required.md
- rules/aip0203/required.go
- rules/aip0203/required_test.go
google.aip.dev issue: https://github.com/aip-dev/google.aip.dev/issues/411
Given a field:
```proto
message ExportBookRequest {
bool enable_encryption = 1;
// Required if enable_encryption is set to true.
string encryption_key = 2;
}
```
`encryption_key` should not be annotated with `REQUIRED` since it is
only necessary if `enable_encryption` is set. This change ensures that
if a field comment contains 'required if', it will not trigger a linter
error.
Note there are other phrases that could logically apply (e.g. 'Only
required when'), but the resulting regex would be difficult to maintain.
> feat: Support 'conditionally' required fields.

- rules/aip0132/request_show_deleted_required.go
- rules/aip0132/request_show_deleted_required_test.go
> fix: Prevent AIP-132 request-show-deleted-required rule from crashing on non-message fields

- docs/rules/0191/proto-package.md
- rules/aip0191/aip0191.go
- rules/aip0191/proto_package.go
- rules/aip0191/proto_package_test.go
Checks that the proto package corresponds tot he directory structure of the proto file. If the proto file name is at the root, it is ignored.
> feat: add proto-package check to AIP-191

- rules/aip0191/proto_package.go
- rules/aip0191/proto_package_test.go
> fix: Use OS-specific file separator in core::0191::proto-package rule

- rules/aip0126/unspecified.go
- rules/aip0126/unspecified_test.go
Fixes #871 by allowing `UNKNOWN` as the first value in an enum.
Note: If this rule emits a problem, it will suggest using the `_UNSPECIFIED` format for the first value and not `UNKNOWN`. Using `UNKNOWN` is an exception for a specific case and that should be discussed with reviewers/referenced from the AIP.
> fix(AIP-126): allow first enum value UNKNOWN

- cmd/api-linter/integration_test.go
This makes the integration test independent of particular rule sets.
For example, it allows creation of rules in other spaces that may generate
violations for the sample API definition.
> fix: disable all rules instead of core rules only

- README.md
This change makes it so that upon clicking the ci badge in the root README and therefore on the homepage of the repo, the user is redirected to the ci workflows page rather than a view of the badge itself as svg.
> Change destination of ci badge click to show ci

- .github/workflows/release.yaml
It is sometimes useful to be able to create a release without having to wait for the scheduled run of this action.
> Allow releases to be triggered manually

- rules/internal/utils/http.go
Escape `}`. Works without but other RegExp's here do it and I don't know that I like that it does work without it because what about `{2}` or `{0,2}`. Anyway, let's make it consistent and explicit.
> fix: Make plainVar RegExp explicit and consistent.

- docs/index.md
this change updates the installation docs to use the more recent `go install`.
from the go 1.17 doc referenced below:
> go get prints a deprecation warning when installing commands outside the main module (without the -d flag). go install cmd@version should be used instead to install a command at a specific version, using a suffix like @latest or @v1.2.3. In Go 1.18, the -d flag will always be enabled, and go get will only be used to change dependencies in go.mod.
ref: https://tip.golang.org/doc/go1.16#go-command
ref: https://tip.golang.org/doc/go1.17#go-command
> chore(install): update to use go install

- .github/release-tool/changelog.go
This means that `chore` commits will precipitate a patch release.
> chore: include chore commits in visible list

- docs/rules/0191/filenames.md
- rules/aip0191/aip0191.go
- rules/aip0191/filenames.go
- rules/aip0191/filenames_test.go
> fix(AIP-191): valid characters in filename

- docs/rules/0123/resource-definition-pattern.md
- docs/rules/0123/resource-definition-type-name.md
- docs/rules/0123/resource-definition-variables.md
- rules/aip0123/aip0123.go
- rules/aip0123/resource_definition_pattern.go
- rules/aip0123/resource_definition_pattern_test.go
- rules/aip0123/resource_definition_type_name.go
- rules/aip0123/resource_definition_type_name_test.go
- rules/aip0123/resource_definition_variables.go
- rules/aip0123/resource_definition_variables_test.go
- rules/aip0123/resource_pattern.go
- rules/aip0123/resource_variables.go
Since `google.api.resource_definition` annotations are the "headless" form of a `google.api.resource` (headless in that there is no message defined in the API to back them i.e. this is a resource from another API), their fields should be linted in mostly the same way. This copies three different rules already implemented for `google.api.resource` and adjusts them for `google.api.resource_definition`. Some of the code is almost exactly the same, so I abstracted those bits into local functions to share between the message and file level versions of these annotations.
Fixes #949 and does the same thing for some other rules in this AIP that apply to `google.api.resource_definition`.
> feat(AIP-123): lint resource_definition annotations

- .github/renovate.json5
Changes from RenovateBot that update this repos dependencies will no longer be grouped in a single Pull Request (like it is [today](https://github.com/googleapis/api-linter/pull/926)). Instead, they will come in as individual Pull Requests.
> chore: remove renovate grouping

- docs/rules/cloud.md
- docs/rules/index.md
- lint/config.go
- lint/config_test.go
- lint/rule_enabled.go
- lint/rule_groups.go
- lint/rule_urls.go
- lint/rule_urls_test.go
This lays the ground work to have `"cloud"` as an AIP group for linter rules.
> feat: add cloud AIP group

- rules/aip0132/resource_reference_type.go
- rules/aip0132/resource_reference_type_test.go
[yaqs/6147033380028416](http://yaqs/6147033380028416) is an example of an API that attempted to annotate a List `parent` field with a resource_reference to a message that isn't a resource. 
The resource_reference type should only be linted if the response message is a resource.
> fix(AIP-132): lint OnlyIf the response message is a resource

- .github/workflows/ci.yaml
Switches use of `golangci-lint` to the GitHub Action form and switches to using the `setup-go` action as it is the preferred means of setting up a Go environment in our projects.
> chore(ci): fix golangci-lint and setup-go steps

- docs/rules/0122/resource-collection-identifiers.md
- rules/aip0122/resource_collection_identifiers.go
- rules/aip0122/resource_collection_identifiers_test.go
Resource patterns must start with lowercase letters per [AIP-122](https://google.aip.dev/122).
Fixes #994
> feat(AIP-122): resource patterns must start with lowercase letter

- cmd/api-linter/cli.go
- cmd/api-linter/github_actions.go
- cmd/api-linter/github_actions_test.go
In this mode, the linter runs and prints out to stdout following the
GitHub "::error" annotation to attach an error to a particular file on a
particular line.
GitHub's documentation on the matter.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
> feat: add GitHub error output format option

- cmd/api-linter/github_actions.go
- cmd/api-linter/github_actions_test.go
Turns out that real lint errors can come in many forms. This now only
prints out the information that is present instead of out of bounds
`panic`ing.
> fix: not all findings have column info

- cmd/api-linter/github_actions.go
- cmd/api-linter/github_actions_test.go
- lint/problem.go
Include linter rule URI in findings for GitHub Action format.
> fix: Render URIs in github actions links

- cmd/api-linter/github_actions.go
- cmd/api-linter/github_actions_test.go
The documentations[0] very clearly states that you should use a comma to
delimit the various sections of a lint comment (line,col,title,etc.).
However I completely missed the mark on that one. This uses the correct
delimiter which should hopefully make the annotations show up properly.
[0] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
> fix: delimit github lint components correctly

- .github/workflows/release.yaml
As mentioned in #991, building locally using `gox -osarch darwin/arm64 -output api-linter ./...` works just fine (which isn't surprising as there's already Linux ARM support).
> ci: build Darwin/arm64 artifacts in release

- rules/aip0203/aip0203.go
- rules/aip0203/immutable.go
- rules/aip0203/immutable_test.go
- rules/aip0203/input_only.go
- rules/aip0203/input_only_test.go
- rules/aip0203/optional_consistency.go
- rules/aip0203/optional_consistency_test.go
- rules/aip0203/optional_test.go
- rules/aip0203/output_only.go
- rules/aip0203/output_only_test.go
- rules/aip0203/required_test.go
The `etag` field should be excluded from the AIP-203  rules, because it is not supposed to be given any behavior annotations per AIP-154.
Fixes #977.
In a separate PR perhaps we should add a rule to enforce that `etag` should not have any field_behavior annotations at all.
> fix: exclude etag from field_behavior lints

- docs/rules/0123/name-never-optional.md
- rules/aip0123/aip0123.go
- rules/aip0123/name_never_optional.go
- rules/aip0123/name_never_optional_test.go
AIP-123 does not explicitly state that the name field must not be proto3_optional, but fundamentally it should never be. The use of proto3_optional is outlined in AIP-149, which states that it must only be used when the unset/default empty value holds meaning. In this case, an empty string `""` is not a valid resource name and must never be differentiated as a valid value.
Fixes #1010
> feat: name field must never be proto3_optional

- .github/workflows/release.yaml
The `release` job for `darwin/arm64` failed because the `gcc` toolchain for `darwin/arm64` is not available on ubuntu by default. Apparently Go 1.16 added support for this compilation target, so I'm updating to Go 1.18 so as to 1. capture this change and 2. get the release job a little more up to date with modern Go version. I built the X-compiled binary locally with no issue.
We should look at upping the version used across CI and in our `go.mod`.
> fix(ci): use go 1.18 in release job

- .github/workflows/release.yaml
When switching CI to Go 1.18, I forgot to switch the use of `go get` for installing binaries to `go install`. This caused the last release to fail because the `gox` tool wasn't available.
Should address the lack of binaries pointed out by #1019.
> fix(ci): use go install for build deps

- docs/rules/0191/file-layout.md
Clarifies the AIP-191 `file-layout` rule documentation by relating the finding modes more directly to the leading paragraph providing the context of each mode. 
Fixes #1031
> fix(AIP-191): clarify file-layout rule doc

- go.mod
- go.sum
- locations/locations_test.go
- locations/method_locations.go
- rules/internal/testutils/parse.go
- rules/internal/utils/extension.go
Renovate tried to update `genproto` in #1037, but that change includes the deprecation and aliasing of the `longrunning` package to its new location in `cloud.google.com/go/longrunning/autogen/longrunningpb`. The deprecation notices on `genproto` triggered linter warnings. So rather than have the Go linter be upset about the deprecated deps on every PR, I am fixing it here with the genproto update, and subsequent direct dependency on the new lro stubs package.
> chore(deps): switch to new lro stub pkg

- docs/rules/0136/http-name-variable.md
- docs/rules/0136/http-parent-variable.md
- rules/aip0136/aip0136.go
Disable the AIP-136 rules `http-name-variable` and `http-parent-variable` after discussion on https://github.com/aip-dev/google.aip.dev/issues/955 identified that these rules were insufficient and not tied to specific guidance.
Fixes #1023 by disabling it.
Note: The rule documentation has a notice that will be highlighted/formatted to stand out.
> feat(AIP-136): disable http-name-variable and http-parent-variable

- lint/lint.go
- lint/problem.go
The `lint` framework depends on each `Problem` reporting the `Descriptor` that created the `Problem` for information such as source code location and leading comments (e.g. for local rule exceptions). Parts of the framework work on the assumption that `Descriptor` will always be present on the `Problem`. This is a fair assumption to make and we should enforce it, returning an error if a `Problem` is reported _without_ a `Descriptor`. There is no reason _not_ to include the `Descriptor`.
> feat: require Problem to have Descriptor

- docs/rules/0127/http-template-syntax.md
- rules/aip0127/aip0127.go
- rules/aip0127/http_template_syntax.go
- rules/aip0127/http_template_syntax_test.go
Part of #1049 
This constructs a regex containing the syntax rules defined [here](https://github.com/googleapis/googleapis/blob/83c3605afb5a39952bf0a0809875d41cf2a558ca/google/api/http.proto#L224). This approach is trickier to debug than writing a parser. However, it seems likely that with sufficient testing this rule will not require much debugging, especially since it does not seem the syntax rules will change anytime soon.
> feat(AIP-127): Validate HTTP pattern syntax

- docs/rules/0127/http-template-pattern.md
- docs/rules/0127/http-template-syntax.md
- rules/aip0127/http_template_syntax.go
- rules/aip0127/http_template_syntax_test.go
- rules/internal/utils/http.go
Fixes http://b/262723883 by removing the `{$api_version}` template variable from the HTTP patterns before validating them. This is the simplest way to not trip up on such templates. If the pattern uses the wrong version template, then it won't match/replace and the rule will likely warn that the pattern is wrong.
Also fix an redirect loop in the docs for http-template-syntax and http-template-pattern rule pages. The `redirect_from` should be a four digit value, lead by 0 if the AIP number is 3 digits e.g. `0127`. That is too easy to mess up, I wonder if we can verify this somehow...fixes http://b/262448725
> fix(AIP-127): account for api_version template

- rules/aip0192/absolute_links.go
The `absolute-link` rule did not include a location on the resulting finding. We can give a rough estimate on the location of the specific descriptor/element which has the offending comment.
This fixes an internally filed issue http://b/263138317.
> fix(AIP-192): include location in absolute-link finding

- rules/aip0123/resource_type_name.go
- rules/aip0123/resource_type_name_test.go
fixes #1066. See AIP-0123 for details.
> feat(AIP-123): add validation of uppercase resource type

- rules/aip0214/resource_expiry.go
- rules/aip0214/resource_expiry_test.go
Only resources need the API-214 resource-expiry check.
fixes #1073
> fix(AIP-214): scope resource-expiry to resources

- .github/workflows/ci.yaml
- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
- lint/problem.go
- lint/rule.go
- lint/rule_urls.go
- lint/rule_urls_test.go
- rules/aip0152/aip0152.go
- rules/aip0152/http_uri_suffix.go
- rules/aip0152/http_uri_suffix_test.go
- rules/aip0162/aip0162.go
- rules/aip0164/http_uri_suffix_test.go
- rules/aip0165/http_uri_suffix_test.go
- rules/aip0233/aip0233.go
- rules/aip0233/http_method_test.go
- rules/aip0233/http_uri_suffix.go
- rules/aip0233/http_uri_suffix_test.go
- rules/aip0233/plural_method_name_test.go
- rules/aip0234/aip0234.go
- rules/aip0234/http_method_test.go
- rules/aip0234/http_uri_suffix.go
- rules/aip0234/http_uri_suffix_test.go
- rules/aip0234/plural_method_name_test.go
- rules/aip0235/aip0235.go
- rules/aip0235/http_uri_suffix.go
- rules/aip0235/http_uri_suffix_test.go
- rules/aip0235/plural_method_name_test.go
- rules/internal/utils/http.go
using staticcheck as golint has been deprecated.
golint errors ignore comments were also not being
honored, so switching to staticcheck enables the whole
repository pass some form of linter.
Go lint had multiple findings when run on the full codebase.
Fixing those to help ensure future contributors have less friction
and confusion wondering if the errors were caused by them.
> chore: switch to statticcheck, fix linting

- cmd/api-linter/cli.go
- lint/lint.go
Adds a debug flag to the cli and passes it to lint.Linter. If enabled, when a panic is recoverd, the stack will be printed by the runtime/debug package.
Closes #1086
> feat: enable better debugability for linting

- lint/lint.go
- lint/lint_test.go
Add a test for the Debug option. In so doing, found a bug: it was not actually applied.
Closes #1086
> fix: apply opts and test

- .github/quality-checker/rule_documented.go
- .github/quality-checker/rule_name.go
- .github/quality-checker/rule_registered.go
- .github/workflows/ci.yaml
- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
- lint/config.go
- lint/config_test.go
This is a duplicate of #1085, which could not
be merged automatically.
removing references to ioutil as the package has been deprecated and now just shims to functions in io / os.
> chore: Update staticcheck-action action to v1.3.0

- cmd/api-linter/cli.go
- cmd/api-linter/integration_test.go
- lint/lint.go
- lint/lint_test.go
- lint/rule_enabled.go
- lint/rule_enabled_test.go
For strict enforcement of AIPs across an organization, it's valuable to disable the ability to have text in the proto disable linter rules.
> feat: add the ability to ignore comment disables

- docs/rules/0122/resource-id-output-only.md
- rules/aip0122/aip0122.go
- rules/aip0122/resource_id_output_only.go
- rules/aip0122/resource_id_output_only_test.go
- rules/aip0123/resource_type_name.go
- rules/internal/utils/extension.go
- rules/internal/utils/extension_test.go
Adds rule to check that either Resource ID field allowed by AIP-122 is classified as `OUTPUT_ONLY`.
See https://github.com/aip-dev/google.aip.dev/pull/1040.
> feat(AIP-122): enforce output_only resource IDs

- docs/rules/0216/state-field-output-only.md
- rules/aip0216/aip0216.go
- rules/aip0216/state_field_output_only.go
- rules/aip0216/state_field_output_only_test.go
AIP-216 calls for `State` enums to be
OUTPUT_ONLY.
Add a rule that requires OUTPUT_ONLY for fields which have an enum type ending with `State`.
Note that the AIP does not mention rules for the *field name* for state fields, we ignore the field name in the linter.
> feat(AIP-216): Enforce OUTPUT_ONLY behavior for State enums

- rules/aip0133/response_message_name.go
- rules/aip0134/response_message_name.go
- rules/aip0135/response_message_name.go
- rules/aip0162/rollback_response_message_name.go
- rules/aip0162/rollback_response_message_name_test.go
- rules/aip0164/response_message_name.go
- rules/aip0233/response_message_name.go
- rules/aip0234/response_message_name.go
- rules/aip0235/response_message_name.go
- rules/internal/utils/declarative_friendly.go
- rules/internal/utils/type_name.go
Allow `Rollback` RPCs to use LRO, and lint the `response_type` as if it were the RPC return type.
Do some light refactoring of "is a longrunning operation" checks, favoring a new helper method.
Fixes #1063
> feat(AIP-162): lint operation_info response_type

- rules/aip0151/lro_response_type.go
- rules/aip0151/lro_response_type_test.go
Allow `BatchDelete` to use `Empty` response as is allowed in AIP-235.
Fixes #1092
> fix(AIP-151): allow batch delete an Empty response

- docs/rules/0148/use-uid.md
- rules/aip0148/aip0148.go
- rules/aip0148/use_uid.go
- rules/aip0148/use_uid_test.go
The standard field for the Resource ID segment within a resource is `uid`, not `id` per AIP-148. So let's enforce that.
Fixes #1068
> feat(AIP-148): use uid instead of id

- docs/rules/0133/request-id-field.md
- rules/aip0133/request_id_field.go
- rules/aip0133/request_id_field_test.go
Corresponds to the change to https://github.com/aip-dev/google.aip.dev/pull/1019.
resource_id is now required regardless of declarative_friendly.
fixes #1107
> feat(AIP-133): add request-id-field for non-df API

- rules/aip0122/name_suffix.go
- rules/aip0122/name_suffix_test.go
The field `display_name` is an allowed use of `_name` suffix. I've seen some Custom Methods that create multiple resources and want to allow specifying the resulting `display_name` fields, so they prefix them with the resource it would correlate to post-creation e.g. `instance_display_name` and `network_display_name`, while other resource fields would be populated on behalf of the user (if there are any to begin with). 
Fixes http://b/270956831
> fix(AIP-122): allow display_name suffix

- rules/aip0158/response_plural_first_field.go
- rules/aip0158/response_plural_first_field_test.go
- rules/internal/utils/resource.go
- rules/internal/utils/resource_test.go
As we start to require `plural` in `google.api.resource`, we should referencing it in rules that attempt to pluralize words for things like field names or collection IDs. This is a reasonable heuristic to use for the AIP-158 `response-plural-first-field` when that first field is a resource.
Fixes http://b/271479822
> fix(AIP-158): reference resource plural for field name

- rules/aip0203/field_behavior_required.go
- rules/internal/utils/method.go
copyright was being mis-interpreted as package comments.
> chore: fix linting errors

- docs/rules/0123/resource-name-components-alternate.md
- docs/rules/0131/request-required-fields.md
- docs/rules/0132/request-required-fields.md
- docs/rules/0133/request-required-fields.md
- docs/rules/0134/request-required-fields.md
- docs/rules/0135/request-required-fields.md
- docs/rules/0203/field-behavior-required.md
some pages were not rendering (warnings in the serving), while
others were categorized under an incorrect name.
> chore: fix typos

- rules/aip0133/request_required_fields.go
- rules/aip0133/request_required_fields_test.go
Change the filter for the resource message field to compare the field type to the response type (which should be the resource for a Standard Create), instead of a case sensitive derivation of the resource type name or singular name.
Add some tests for when `singular` is set.
Should be a fix for item 2 of http://yaqs/4607975166683643904 (internal link)
> fix(AIP-133): compare types instead for message fields

- rules/aip0134/request_required_fields.go
- rules/aip0134/request_required_fields_test.go
Refactors `core::0134::request-required-fields` into a `MethodRule` so as to get access to the expected response type a.k.a the exact resource type being updated. Then fix the message type field check to compare the Resource message type to the field message type if applicable. Similar to #1165
> fix(134): compare message types for required fields

- rules/aip0203/field_behavior_required.go
- rules/aip0203/field_behavior_required_test.go
This commit tests that the logic works across multiple files and also lints response messages that are resources or of depth greater than 0.
> feat: test across multiple files, ignore name on resource

- docs/rules/0203/field-behavior-required.md
- rules/aip0203/field_behavior_required.go
- rules/aip0203/field_behavior_required_test.go
Although all request messages **must** be annotated, this linter only verifies
messages that are in the same package as some upstream protos (e.g. common
protos) may be difficult to modify.
> fix(AIP-203): lint non-maps and same package

- docs/rules/0203/field-behavior-required.md
- rules/aip0203/field_behavior_required.go
- rules/aip0203/field_behavior_required_test.go
OneOf fields should not be checked for annotations, as they are implicitly optional.
However, if a sub-message is used in the OneOf,
it should be verified.
> fix(AIP-203): no check for OneOf fields

- rules/aip0158/response_plural_first_field.go
[Internal feedback](http://b/289577053) pointed out that the `response-plural-first-field` finding was reported on the message, rather than the field itself, unlike other field-specific rules. It was setting the wrong location.
> fix(AIP-158): emit first field plural on field

- rules/aip0142/aip0142.go
- rules/aip0142/time_field_names.go
- rules/aip0142/time_field_names_test.go
[Internal feedback](http://b/290222132) reported this finding as not useful on a field like `string updated_value`. I agree, it does not make sense for this rule to be linting the name of non-timestamp fields. The `time-field-type` rule already catches fields-like-timestamps that aren't typed as such, which when fixed would result in this rule being fired.
> fix(AIP-142): only lint name of timestamp fields

- rules/aip0142/time_field_names.go
- rules/aip0164/resource_expire_time_field.go
- rules/aip0164/resource_expire_time_field_test.go
Updating checking for purge_time to align with
https://github.com/aip-dev/google.aip.dev/pull/1169.
Continued to ignore expire_time for soft-deleted resources
for backwards-compatibility.
> feat(AIP-142): adding purge_time field

- docs/rules/0135/response-message-name.md
- rules/aip0135/response_message_name.go
- rules/aip0135/response_message_name_test.go
AIP-135 and AIP-128 have changed to not suggest soft-deleted
resources. This updates the linter to that recommendation.
> fix(AIP-135): removing df check in response-message-name

- docs/rules/0135/force-field.md
- rules/aip0135/aip0135.go
- rules/aip0135/force_field.go
- rules/aip0135/force_field_test.go
- rules/internal/utils/extension.go
- rules/internal/utils/extension_test.go
Adds rule `core::0135::force-field` that will complain if the Standard Delete request for a resource that parents other resources does not have a `bool force` field to implement Cascading Delete with.
Also adds a helper for collecting the child resources of a given resource, within the same service.
Fixes #1188
> feat(AIP-135): add cascading delete force-field rule

- locations/field_locations.go
- locations/field_locations_test.go
Similar to the `MethodOption` helper, this enables retrieving source code info for an arbitrary Field option.
> fix(locations): add arbitrary field option helper

- .github/workflows/release.yaml
- .release-please-config.json
- CHANGELOG.md
- CHANGES.md
Needed to move the `checkout` step ahead of the `setup-go` step in order to reference the `go.mod` in the project. Also attempts to configure the change log path to CHANGELOG.md instead of the default CHANGES.md.
> fix(ci): fix release asset job

- docs/rules/0192/deprecated-comment.md
- rules/aip0192/aip0192.go
- rules/aip0192/deprecated_test.go
The AIP-192 deprecated documentation requirement should apply to all proto file elements. This is critical documentation for users.
AIP-192 update: https://github.com/aip-dev/google.aip.dev/pull/1198
> fix(AIP-192): enforce deprecated comment on all non-file descriptors

- docs/rules/0203/resource-identifier-only.md
- rules/aip0203/aip0203.go
- rules/aip0203/resource_identifier_only.go
- rules/aip0203/resource_identifier_only_test.go
- rules/internal/utils/resource.go
Enforces AIP-203 guidance added in https://github.com/aip-dev/google.aip.dev/pull/1201 that only the resource's name field can have `google.api.field_behavior = IDENTIFIER`.
> feat(AIP-203): disallow IDENTIFIER on non-name

- docs/rules/0203/resource-name-identifier.md
- rules/aip0203/aip0203.go
- rules/aip0203/resource_name_identifier.go
- rules/aip0203/resource_name_identifier_test.go
Enforces AIP-203 guidance added in https://github.com/aip-dev/google.aip.dev/pull/1201 that the resource's name field must have `google.api.field_behavior = IDENTIFIER`.
> feat(AIP-203): add resource name IDENTIFIER enforcement

- docs/rules/0122/embedded-resource.md
- rules/aip0122/aip0122.go
- rules/aip0122/embedded_resource.go
- rules/aip0122/embedded_resource_test.go
- rules/internal/utils/resource.go
- rules/internal/utils/resource_test.go
Disallow embedding resources in other resources, use resource_references instead.
Enforce guidance added in https://github.com/aip-dev/google.aip.dev/pull/1196.
> feat(AIP-122): disallow embedded resource

- rules/aip0121/resource_must_support_get.go
- rules/aip0121/resource_must_support_get_test.go
Ignore methods that look like standard methods but don't actually operate on a resource as a standard method would. This prevents false positive findings related for messages that aren't actually resources but have some standard method lookalikes. Similar to #1235
> fix(AIP-121): ignore standard method lookalikes

- rules/aip0121/resource_must_support_get.go
- rules/aip0121/resource_must_support_get_test.go
- rules/aip0121/resource_must_support_list.go
- rules/aip0121/resource_must_support_list_test.go
- rules/internal/utils/method.go
When checking for missing standard methods, ignore streaming methods as they can never be standard methods. Based on https://github.com/googleapis/api-linter/pull/1250#discussion_r1322469624.
> fix(AIP-121): ignore streaming lookalikes

- rules/aip0203/resource_name_identifier.go
- rules/aip0203/resource_name_identifier_test.go
As [reported internally](https://b.corp.google.com/issues/302714576), the suggestion from this finding replaces the entire line rather than just adding the extension.
> fix(AIP-203): remove resource name identifier suggestion

- docs/rules/0155/index.md
- docs/rules/0155/request-id-format.md
- rules/aip0155/aip0155.go
- rules/aip0155/aip0155_test.go
- rules/aip0155/request_id_format.go
- rules/aip0155/request_id_format_test.go
- rules/rules.go
Enforces new AIP-155 guidance that says `request_id` should have `(google.api.field_info).format = UUID4`.
> feat(AIP-155): enforce format uuid4 guidance

- docs/rules/0148/uid-format.md
- go.mod
- go.sum
- rules/aip0148/aip0148.go
- rules/aip0148/uid_format.go
- rules/aip0148/uid_format_test.go
As mandated in AIP-148, the `uid` field **must** have `(google.api.field_info).format = UUID4`. This rule enforces that.
Also fix incorrect doc title for `use-uid` rule doc.
> feat(AIP-148): add uid-format rule

- docs/rules/0148/ip-address-format.md
- rules/aip0148/aip0148.go
- rules/aip0148/ip_address_format.go
- rules/aip0148/ip_address_format_test.go
As mandated in AIP-148, and IP Address field must have `(google.api.field_info).format` with one of the IP Address formats. This rule enforces that.
> feat(AIP-148): lint IP Address field format

- rules/aip0203/resource_name_identifier.go
- rules/aip0203/resource_name_identifier_test.go
This proto reproduces the following crash:
```proto
syntax = "proto3";
package dummy;
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
message Dummy {
option (google.api.resource) = {
type: "dummy/Dummy"
pattern: "dummies/{dummy}"
};
string other = 1 [(google.api.field_behavior) = REQUIRED];
}
```
```sh
goroutine 1 [running]:
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/googleapis/api-linter/lint.(*Linter).runAndRecoverFromPanics.func1()
/Users/william/dev/oss/api-linter/lint/lint.go:125 +0x50
panic({0x102971740?, 0x102e6e5f0?})
/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:914 +0x218 …
```
> fix(AIP-203): avoid panic if name field is missing

- rules/aip0133/http_uri_resource.go
- rules/aip0133/http_uri_resource_test.go
If there is a Custom Method that looks like a Standard Create e.g. `CreateAndCheckoutBook`, it will have a HTTP suffix like `.../books:createAndCheckout`. For a resource path like `books/{book}` this would be valid, sans custom method suffix, because the collection IDs match at the end of the HTTP path, but the rule naively included the custom method suffix and expects the resource pattern to look like `books:createAndCheckout`. While using Standard Method verbs for Custom Methods is not allowed, it happens occasionally, and ApiLinter shouldn't emit garbage as a result. 
Address [internal issue](http://b/309923830).
> fix(AIP-133): lint http collection ID for lookalikes

- docs/index.md
The help message output in the usage section has been outdated for quite a while. This commit updates it with the latest output of `api-linter -h`.
> docs: update help message in usage section

- rules/aip0123/resource_pattern.go
- rules/aip0123/resource_pattern_test.go
Closes https://github.com/googleapis/api-linter/issues/1090.
> fix(AIP-123): disallow spaces in pattern

- cmd/api-linter/cli.go
- go.mod
- lint/problem.go
- lint/problem_test.go
- lint/rule.go
- lint/rule_enabled.go
- lint/rule_enabled_test.go
- locations/descriptor_locations.go
- locations/field_locations.go
- locations/file_locations.go
- locations/file_locations_test.go
- locations/locations.go
- locations/message_locations.go
- locations/method_locations.go
- rules/aip0123/duplicate_resource.go
- rules/aip0123/resource_pattern.go
- rules/aip0123/resource_variables.go
- rules/aip0191/file_option_consistency.go
- rules/aip0191/file_option_consistency_test.go
Swap out instances of the deprecated protobuf-go v1 module with drop-in replacement using protobuf-go v2 module.
> chore: replace v1 proto-go with v2

- docs/rules/0123/resource-annotation.md
- rules/aip0123/aip0123.go
- rules/aip0123/resource_annotation_test.go
It is reasonable to allow the use of a `name` field in a nested message since nested messages are most often authored as a small piece of a larger message, thus never really candidates for being a resource.
> fix(AIP-123): allow name in nested messages

- rules/aip4232/required_fields.go
- rules/aip4232/required_fields_test.go
When a method signature contains a nested field of a message type field that is required in the top level request message, that should be sufficient to fulfill the "all required fields in method signature" requirement.
Internal bug b/325252841
> fix(AIP-4232): support nested field of required field

- docs/rules/0191/java-outer-classname.md
Addresses confusion in [internal bug](http://b/318621685) by removing ambiguity in the linter rule docs allowing for `java_out_classname` variance when AIP-191 states it **should** be named as the proto.
> docs(AIP-191): remove ambiguity in java_outer_classname

- rules/aip0133/request_required_fields.go
- rules/internal/utils/method.go
This addresses a nil dereferencing error due to `ot` being `nil` in https://github.com/andrei-scripniciuc/api-linter/blob/f6108f07532aae07c4f305c7da99092f0114cea2/rules/aip0133/request_required_fields.go#L50
> feat(AIP-133): ignore create methods with invalid LRO response types

- .github/renovate.json5
renovate uses latest Go version, but that means it will be tidied with 1.22 which adds `toolchain` directive to the `go.mod` which `Go 1.20` tools (i.e. CI) do not understand.
> chore(deps): force renovate to use Go 1.20

- .github/renovate.json5
Blocks updates to `stringset` until we migrate to Go 1.21, at which point we can take new versions of it.
> chore(deps): block stringset updates until 1.21

- rules/internal/utils/common_lints.go
- rules/internal/utils/common_lints_test.go
When linting if a field is a oneof, ignore those fields that are proto3_optional, which are wrapped in a synthetic oneof.
Updates #1323
> fix: ignore proto3_optional fields in oneof check

- .github/workflows/release.yaml
Disable `CGO` during X-platform compilation to make truly x-platform binaries.
Updates #1317
> fix(ci): build binaries with CGO_ENABLED=0

- rules/aip0203/field_behavior_required.go
- rules/aip0203/field_behavior_required_test.go
Addresses b/334162004 under allowance in AIP-154:
> The etag field on the resource **should not** be given any behavior annotations.
> fix(AIP-203): resource etag should not have behavior

- docs/rules/0136/request-message-name.md
- rules/aip0136/aip0136.go
- rules/aip0136/request_message_name.go
- rules/aip0136/request_message_name_test.go
[AIP-136](https://google.aip.dev/136)
> Custom methods should take a request message matching the RPC name, with a `Request` suffix.
> feat(AIP-136): request message name

- docs/rules/0136/response-message-name.md
- rules/aip0136/aip0136.go
- rules/aip0136/response_message_name.go
- rules/aip0136/response_message_name_test.go
[AIP-136](https://google.aip.dev/136)
> - Custom methods should return a response message matching the RPC name, with a Response suffix.
>   - When operating on a specific resource, a custom method may return the resource itself
> feat(aip-136): response message name

- rules/aip0136/response_message_name.go
- rules/aip0136/response_message_name_test.go
- rules/internal/utils/common_lints.go
- rules/internal/utils/common_lints_test.go
The common lint for response message name matching needs to better handle LRO Methods which have their response message encoded in the `google.longrunning.operation_info` annotation.
This fixes the common lint to properly compare the response_type name instead of the rpc return type in the LRO case, as well as the AIP-136 implementation to warn on the proper spot.
Internal bug b/342434484
cc: @liveFreeOrCode just an fyi - the helper we used had a little bug in it that would let it fall through to the finding logic on valid RPCs using LRO. I should've asked for LRO case in the tests! my bad
> fix(AIP-136): handle LRO response names

- rules/aip0136/aip0136.go
- rules/aip0136/http_body.go
- rules/aip0136/http_method.go
- rules/aip0136/http_method_test.go
- rules/aip0136/http_name_variable.go
- rules/aip0136/http_parent_variable.go
- rules/aip0136/http_uri_suffix.go
- rules/aip0136/http_uri_suffix_test.go
- rules/aip0136/request_message_name.go
- rules/aip0136/response_message_name.go
- rules/aip0136/response_message_name_test.go
- rules/internal/utils/method.go
- rules/internal/utils/method_test.go
There is a problem with the Response Message Name linter of AIP-136 currently.
For reference: https://github.com/googleapis/api-linter/blob/main/rules/aip0136/response_message_name.go
This, and all linter methods in aip0136 used a method `isCustomMethod`.  The logic of this method is incomplete/incorrect. It assumed anything with a `":"` in it's URI was considered a custom method.  But, according to https://google.aip.dev/130, Batch methods are also considered Standard methods.  Batch methods have the following URI segments: `:batchGet`, `:batchUpdate`, `:batchCreate` and `:batchDelete`.
What happens?
```proto
service Library {
// This fails the aip0136 response_message_name lint rule
rpc BatchDeleteBooks(BatchDeleteBooksRequest) returns (google.protobuf.Empty) {
option (google.api.http) …
```
> fix(aip-130): identify standard and custom methods

- docs/rules/0123/resource-pattern-plural.md
- rules/aip0123/aip0123.go
- rules/aip0123/resource_pattern_plural.go
- rules/aip0123/resource_pattern_plural_test.go
- rules/aip0123/resource_pattern_singular.go
- rules/aip0123/resource_pattern_singular_test.go
Lint for the `plural` appearing as the collection segment in resource patterns. Special handling for nested resource collections that potentially stutter with the pattern, affording a reduced collection segment in the pattern. See #1403 for more details.
The nested plural form is derived in a round about way where we check to see if the parent resource singular (via the resource ID segment) is a prefix of the child collection segment. We use the parent singular because the child plural wouldn't use the parent plural as the prefix in a "compound"/nested name, it would use the parent singular. This prefix is trimmed if it matches, leaving a reduced child collection name that is already pluralized.
For internal bug http://b/343466943
> feat(AIP-123): resource collection matches plural

- rules/aip0123/resource_pattern_plural.go
- rules/aip0123/resource_pattern_plural_test.go
When there is no `plural` field in the `google.api.resource`, skip check if the plural exists in the `pattern`(s).
> fix(AIP-123): skip resource-pattern-plural when there is no plural

- docs/rules/0135/request-required-fields.md
- rules/aip0135/request_required_fields.go
- rules/aip0135/request_required_fields_test.go
Allow Standard Field `etag` to be `REQUIRED` in Standard Delete.
Updates #1395
> fix(AIP-135): allow required etag in Delete

- rules/aip0133/request_required_fields.go
- rules/aip0134/request_required_fields.go
- rules/aip0136/response_message_name.go
- rules/aip0233/resource_reference_type.go
- rules/internal/utils/common_lints.go
The utility method that resolves the response type descriptor, handling LROs in the process, can return `nil` if either the response type is not resolvable in the protos (very bad) OR the RPC is an LRO that isn't annotated as required by AIP-151 with `google.longrunning.operation_info`. In these cases, anywhere the helper is used should just exit - if the type is unresolvable there are other issues, and if the LRO RPC is unannotated, then AIP-151 rules will warn on that missing annotation.
We definitely shouldn't be going into a `panic`
Updates #1399
> fix: exit rule if response type cannot be resolved

- rules/aip0235/request_unknown_fields.go
- rules/aip0235/request_unknown_fields_test.go
Allow hoisting `allow_missing` to the top level for Batch Delete. It is an allowed field for Standard Delete and it is not necessarily unique to each delete request (like `etag`), so it can be safely hoisted. 
Updates #1404
> fix(AIP-235): allow hosting allow_missing

- rules/aip0123/resource_pattern_singular.go
- rules/aip0123/resource_pattern_singular_test.go
There was a bug in `resource-pattern-singular` for the multi-word nested name reduction singleton case caused by not converting the `snake_case` value from the `nestedName` helper into `lowerCamelCase` - it was comparing a lowerCamelCase pattern suffix against a snake_case expected value.
Added a bunch more tests specifically using a type name with more than two words for extended matching.
Internal bug report: http://b/359848757
> fix(AIP-123): multiword singleton reduction

- rules/internal/utils/message.go
- rules/internal/utils/message_test.go
Updates all `List` request/response regular expressions to expect a capital letter following `"List"` so as to avoid capturing verbs that start with `"List"`, but which are not `List`, like `"Listen"`.
This is a reasonable refinement to make because all standard Lists are `List{PluralNoun}` so we get `List{PluralNoun}Request` and `List{PluralNoun}Response`. 
Updates #922
> fix(AIP-132): refine List request response regex

- rules/internal/utils/message.go
- rules/internal/utils/message_test.go
Similar to #1420 we need to refine the standard request message regexes.
The examples are a bit contrived, but better to have the refinement than not!
> fix(internal/utils): refine Get, Create, Update, Delete request regex

- docs/rules/0132/response-unknown-fields.md
The field name "unavailable" listed on https://linter.aip.dev/132/response-unknown-fields is incorrect. According to AIP-217, the field should be "unreachable".
> docs(AIP-132): fix incorrect field for AIP-217

- docs/rules/0134/request-mask-required.md
> docs(AIP-134): change mandated to recommended

- rules/aip0162/commit_response_message_name.go
- rules/aip0162/commit_response_message_name_test.go
- rules/aip0162/delete_revision_response_message_name.go
- rules/aip0162/delete_revision_response_message_name_test.go
- rules/aip0162/rollback_response_message_name.go
- rules/aip0162/rollback_response_message_name_test.go
- rules/aip0162/tag_revision_response_message_name.go
- rules/aip0162/tag_revision_response_message_name_test.go
Though AIP-162 is a bit in flux, the existing rules for it should be capable of handling an LRO i.e. when checking the response message name. 
This updates all of the relevant rules to handle LRO RPC return types and load the message name from the operation_info annotation if applicable. Note: We cannot provide an actionable `Suggestion` when the finding pertains to the `operation_info` because we cannot accurately target the `response_type` field. 
The same code is used consistently in a few places in this PR as well as in other rules. We may want to consider how we can centralize `Finding` construction when it could be in the RPC return type section or the `operation_info`.
Internal bug http://b/367699275
> fix(AIP-162): handle LRO in response name rules

- rules/aip0136/response_message_name_test.go
- rules/aip0162/aip0162.go
- rules/aip0162/commit_http_body.go
- rules/aip0162/commit_http_method.go
- rules/aip0162/commit_http_uri_suffix.go
- rules/aip0162/commit_request_message_name.go
- rules/aip0162/commit_response_message_name.go
- rules/aip0162/delete_revision_http_body.go
- rules/aip0162/delete_revision_http_method.go
- rules/aip0162/delete_revision_http_uri_suffix.go
- rules/aip0162/delete_revision_request_message_name.go
- rules/aip0162/delete_revision_response_message_name.go
- rules/aip0162/rollback_http_body.go
- rules/aip0162/rollback_http_method.go
- rules/aip0162/rollback_http_uri_suffix.go
- rules/aip0162/rollback_request_message_name.go
- rules/aip0162/rollback_response_message_name.go
- rules/aip0162/tag_revision_http_body.go
- rules/aip0162/tag_revision_http_method.go
- rules/aip0162/tag_revision_http_uri_suffix.go
- rules/aip0162/tag_revision_request_message_name.go
- rules/aip0162/tag_revision_response_message_name.go
- rules/internal/utils/method.go
- rules/internal/utils/method_test.go
This ensures that the `IsCustomMethod` check ignores the "standard" AIP-162 Revision RPCs - these shouldn't be linted as custom methods generally, they have their own rules defined by AIP-162.
Also refactors all of the revision method regexes and capturing logic into the (internal) utilities package.
Internal bug http://b/367697721
> fix(AIP-136): ignore revision methods

- .github/workflows/ci.yaml
- locations/locations.go
- locations/locations_test.go
Refactors internal source code info registry for the `locations` package to leverage a `synx.Mutex` in protecting the `map`s containing the descriptor/path to SourceCodeInfo pairs. Uses the "[mutex hat](https://github.com/go-critic/go-critic/issues/465)" pattern for naming/commenting.
Adds a simple concurrency test to run with `-race`. Note: Running this same test on `main` produced the data race warning.
Executes unit tests in CI with the `-race` flag.
Updates #1430
> fix(locations): make source info access concurrent safe

- .github/workflows/ci.yaml
- go.mod
- go.sum
To use api-linter with protocolbuffers/protobuf v28 need to update `bufbuild/protocompile` (from v0.10.0 to v0.14.1).
> chore: upgrade go version to 1.21 and bump bufbuild/protocompile to v0.14.1 

- rules/aip0133/method_signature.go
- rules/aip0133/method_signature_test.go
Fix the way that the expected resource field name is derived for Standard Create method_signatures. When the resource field in the request message uses a name that doesn't exactly mirror the resource type/RPC name, the previous logic suggested a method_signature including a field that didn't exist. Since this rule isn't supposed to also govern the field's name itself, just roll with it.
Also fixes the way the output type is evaluated for the resource parent/no-parent case when the response type is an Operation.
Moves the LRO test to its own case.
Addresses internal feedback http://b/372508475
> fix(AIP-133): use resource field in signature suggestion

- docs/Gemfile.lock
An issue was discovered in the WEBrick toolkit through 1.8.1 for Ruby. It allows HTTP request smuggling by providing both a Content-Length header and a Transfer-Encoding header, e.g., "GET /admin HTTP/1.1\r\n" inside of a "POST /user HTTP/1.1\r\n" request. NOTE: the supplier's position is "Webrick should not be used in production."
> fix(deps): upgrade webrick dep

- .github/renovate.json5
Should've been updated when our `go.mod` was updated.
> chore(renovate): update Go runtime version

- .github/workflows/ci.yaml
Simple update to latest patch version, but also disable Staticcheck installing its own Go binary, which is unnecessary because our workflow already install Go based on our `go.mod` file.
> chore(lint): update staticcheck version, disable its go install

- docs/rules/0123/resource-type-message.md
- rules/aip0123/aip0123.go
- rules/aip0123/resource_type_message.go
- rules/aip0123/resource_type_message_test.go
Enforce AIP-123 guidance that the resource type name should match the containing proto message name.
Addresses internal bug: http://b/384544409
> feat(AIP-123): resource type name matches message

- rules/aip0126/unspecified.go
- rules/aip0126/unspecified_test.go
AIP-126 has guidance on prefixing enum values to avoid collisions. This should also apply to the `UNKNOWN` affordance, so that APIs may use `UNKNOWN` in a collision-safe way.
Internal bug http://b/389683192
> fix(AIP-126): Allow prefixed UNKNOWN value

- rules/aip0123/resource_pattern_plural.go
- rules/aip0123/resource_pattern_singular.go
The package comment is defined in `aip0123.go`.
> chore(AIP-123): clean up extraneous package comments

- .github/workflows/release.yaml
Need to explicitly give our release workflow write permissions so that it can upload release assets.
> chore(ci): give release workflow contents.write perm

- cmd/api-linter/cli.go
- cmd/api-linter/cli_test.go
Exclude `"."` from `c.ProtoImportPaths` and append only when building the `protoparse.Parser`. The `"."` was interfering with filename resolution of `protoparse.ResolveFilenames` by preventing cwd relative input protos from being resolved against the cwd-relative import path value. As per the [docs](https://pkg.go.dev/github.com/jhump/protoreflect@v1.16.0/desc/protoparse#ResolveFilenames):
> If a file name is already relative to one of the given import paths, it will be unchanged in the returned slice
By having `"."` present in the import paths during filename resolution, any relative path provided was considered "relative to one of the give import paths" and the user-provided import path(s) that prefix the proto-to-lint filenames are not resolved.
This meant that the protos parsed with …
> fix(cli): exclude cwd from input path resolution

- docs/rules/0215/foreign-type-reference.md
- rules/aip0215/foreign_type_reference.go
- rules/aip0215/foreign_type_reference_test.go
This PR augments AIP-215 rules to look for package mismatches.  It leverages comparisons between a FieldDescriptor that references a Message type, and compares based on the proto package of the two.
Updates: #1018
internal: b/391975695
> feat(AIP-215): augment foreign type checking

- rules/aip0132/request_parent_required.go
- rules/aip0133/http_uri_parent.go
- rules/aip0133/method_signature.go
- rules/aip0133/request_parent_required.go
- rules/aip0133/request_parent_required_test.go
- rules/aip0231/request_parent_field.go
- rules/aip0233/request_parent_field.go
- rules/aip0234/request_parent_field.go
- rules/aip0235/request_parent_field.go
- rules/internal/utils/resource.go
- rules/internal/utils/resource_test.go
#906 should've been closed by previous PRs, but a [user recently reported](https://github.com/googleapis/api-linter/issues/906#issuecomment-2604069831) some issues with it not being completely fixed.
I think they bumped into an edge case where if the resource type wasn't annotated with `google.api.resource`, the logic that checked if the resource was a child resource by looking for _exactly one_ resource ID segment produced a false positive. It should've been checking for `> 1` *and* accounting for the fact that if there are no `pattern`s (or if it is unannotated), it is also not a child resource/has no parent.
I've centralized an updated implementation in `rules/internal/utils` and inverted the logic as per the naming `hasNoParent` -> `HasParent`.
Also cleans up some variable …
> fix(rules): fix HasParent check and utilify it

- docs/rules/0215/foreign-type-reference.md
This appears to be a copy-paste mistake in PR https://github.com/googleapis/api-linter/pull/1467.
> docs(AIP-215): fix incorrect heading for `foreign-type-reference`

- cmd/api-linter/cli.go
Restore explicit proto filename resolution against `"."` removed in #1466. It was removed to facilitate proto filename resolution relative to cwd for file names that weren't prefixed with `./`, but this ended up breaking it for those prefixed with `./`. Instead of attempt to include `"."` as an import path to resolve against alongside the CLI provided ones, we resolve against it afterwards. This is because the `protoparse.ResolveFilenames` will not resolve the file name if it is relative to any of the import paths, but we need it to in case the user provides a mix of import paths and cwd relative values. In this case, the prefix `./` needs to be resolved as well.
Tested it against both reported issue cases.
Updates #1471.
> fix(cli): resolve against cwd separately

- rules/aip0133/response_message_name.go
- rules/aip0133/response_message_name_test.go
- rules/aip0134/response_message_name.go
- rules/aip0134/response_message_name_test.go
- rules/internal/utils/find.go
- rules/internal/utils/find_test.go
The AIP-133 and AIP-134 rules for response message checks were naively comparing the LRO `response_type` value directly, instead of resolving the proto type and comparing the simple message name. This breaks down when a fully qualified name, even within the same package, is specified. Instead, we should attempt to resolve the type and check simple names. This makes an adjustment to the `FindMessage` utility to account for qualified references and matching against imported types that have a matching package. Not sure why this wasn't handled previously.
Internal bug http://b/396418619
> fix(AIP-133/AIP-134): handle qualified lro response type name comparison

- cmd/api-linter/cli.go
Only attempt to resolve against the `--proto-path` import paths if there were some specified, to avoid an error from `protoparse.ResolveFilenames` that requires some import path when provided absolute paths. Still want to keep the `.` resolution separate so that relative input filenames are still able to be resolved against the provided import paths ahead of the attempt to resolve against cwd to avoid proto file name collisions in the subsequent Parse action.
Note: Filed separate bug to come up with a testing harness for the CLI https://github.com/googleapis/api-linter/issues/1479
Updates #1465 again improving on that fix and the one for #1471
> fix(cli): only call ResolveFilenames with ProtoImportPaths if specified

- rules/aip0136/response_message_name.go
- rules/aip0136/response_message_name_test.go
The `core::0136::response-message-name` rule uses a heursitic to verify and account for the _target_ resource type being the response type of the custom method (rather than a message type that aligns with the RPC name). It did this by checking for a `name` field with a `resource_reference` annotation and comparing the `type` there to the `type` of a `google.api.resource` annotation on the response to see if they matched. However, some AIPs recommend using a resource-singular-aligned field name in the request message e.g. the AIP-144 Add/Remove methods. So rather than `AddAuthor`, which returns a `Book`, checking for a `name` field, it will check for a `book` field as well and use that allow the custom method response type to be a `Book` rather than `AddAuthorResponse`.
This still prefers …
> fix(AIP-136): support response msg lint with resource singular name
