- cmd/api-linter/integration_test.go
> Remove `TestEveryRuleHasATestCase`.

- testutil/testutil.go
Also added documentation for why we have these functions in place.
> Added placeholder for additional protoc flags.

- .circleci/config.yml
- lint/rule_info.go
- lint/source_test.go
- rules/descriptor/walk_test.go
The lint errors were reported in issue #115.
> Fixed errors detected by golangci-lint and added it to circleci.

- README.md
Removed the outdated instruction for writing rules to avoid misleading others.
> Removed the outdated instruction for writing rules.

- rules/aip0126/aip0126.go
- rules/aip0126/api0126_test.go
- rules/aip0126/upper_snake_case.go
- rules/aip0126/upper_snake_case_test.go
I did a lot of copy and paste -- I think we can generate some codes, e.g., the initial file structure for each AIP (aip0126.go and aip0126_test.go).
> AIP-126: all enum value must be UPPER_SNAKE_CASE.

- rules/aip0132/message_rules.go
- rules/aip0132/message_rules_test.go
- rules/aip0132/method_rules_test.go
Also caught a bug in the process. :)
> [refactor] Make AIP-132 tests use testutils.Problems.

- lint/rule_aliases.go
- rules/aip0140/abbreviations.go
- rules/aip0140/abbreviations_test.go
- rules/aip0140/aip0140.go
~Uses #207 _and_ #208 as a base.~ Those are merged.
Fixes #167.
> [AIP-140] Abbreviations

- rules/aip0203/aip0203.go
- rules/aip0203/aip203_test.go
- rules/aip0203/input_only.go
- rules/aip0203/input_only_test.go
> Added field annotation input_only rule.

- .github/renovate.json
Even though we ourselves are inconsistent about it.
> [chore] Make Renovate follow conventional commits.

- rules/aip0140/aip0140.go
- rules/aip0140/base64.go
- rules/aip0140/base64_test.go
> [AIP-140] Add base64 rule.

- rules/aip0131/aip0131.go
- rules/aip0131/method_rules.go
- rules/aip0131/method_rules_test.go
- rules/aip0133/aip0133.go
- rules/aip0133/method_rules.go
- rules/aip0133/method_rules_test.go
- rules/aip0134/aip0134.go
- rules/aip0134/method_rules.go
- rules/aip0134/method_rules_test.go
This adds synonym checks for Get, Create, Update.
> Standard method synonyms

- rules/aip0141/types.go
- rules/aip0141/types_test.go
> [AIP-141] Forbidden types.

- rules/aip0133/method_rules.go
- rules/aip0133/method_rules_test.go
- rules/aip0134/method_rules.go
- rules/aip0134/method_rules_test.go
- rules/aip0135/method_rules.go
- rules/aip0135/method_rules_test.go
This adds response type checking when the protobuf response
type is an LRO.
(It also fixes a couple of bugs I found in the process. ;-))
> [AIP-133/134/135] Test LRO responses better.

- lint/problem.go
- lint/rule.go
- rules/rules.go
I am starting to work on making our godoc page awesome.
> [docs] Add documentation.

- rules/aip0122/aip0122.go
- rules/aip0122/aip0122_test.go
- rules/aip0122/http_url_pattern.go
- rules/aip0122/http_url_pattern_test.go
AIP-122: Resource names / HTTP url patterns
> AIP-122: Resource names / HTTP url patterns

- docs/_layouts/default.html
- docs/rules/index.md
This is guess and check sadly; the specific way this works is
specific to the live site.
> [fix] Still trying to fix links.

- docs/rules/core/0131-http-body.md
- docs/rules/core/0131-http-method.md
- docs/rules/core/0131-http-uri-name.md
- docs/rules/core/0131-request-message-name.md
- docs/rules/core/0131-response-message-name.md
- docs/rules/core/0131-synonyms.md
- docs/rules/core/0132-request-message-name.md
- docs/rules/core/0132-response-message-name.md
I forgot these basically everywhere. Whups.
> [fix] Add semicolons after option statements.

- docs/rules/core/0133-response-message-name.md
- docs/rules/core/0134-response-message-name.md
> [fix] Minor docs fix.

- lint/rule.go
> Exclude synthetic message types.

- rules/aip0203/aip0203.go
- rules/rules.go
This registers all unregistered rules caught by the meta-linter
in #318.
> [fix] Fix unregistered rules.

- cmd/api-linter/cli.go
- cmd/api-linter/cli_test.go
- cmd/api-linter/integration_test.go
- docs/index.md
> Rename descriptor set flag.

- go.mod
- lint/rule_name.go
- lint/rule_name_test.go
Removed unused functions and trimmed codes.
> [refactor] Miscellaneous cleanup.

- lint/rule.go
- lint/rule_test.go
> Segment matching in file comments.

- docs/rules/core/0142-time-field-names.md
- docs/rules/core/0203-optional-conflict.md
- docs/rules/core/0203-optional-consistency.md
> [fix] Add missing documentation, correct mis-named document.

- .circleci/meta-linter/main.go
- .circleci/meta-linter/rules_documented.go
Fixes #322.
This PR will currently fail in CI because it caught actual issues, and needs those issues fixed first.
> [feat] Ensure presence of documentation.

- lint/problem.go
- lint/problem_test.go
They were exclusive and it causes an off-by-one issue.
> [fix] Make location ends inclusive.

- docs/rules/0191/java-multiple-files.md
- lint/rule.go
- lint/rule_test.go
- rules/aip0191/aip0191.go
- rules/aip0191/java_multiple_files.go
- rules/aip0191/java_multiple_files_test.go
~This should not be merged until googleapis/aip#360 is.~ That PR is merged.
> [AIP-191] Require `option java_multiple_files = true;`.

- .circleci/config.yml
- .golangci.yml
- cmd/api-linter/cli.go
- lint/config_test.go
- lint/problem.go
- lint/rule.go
- rules/aip0140/reserved_words_test.go
- rules/aip0191/java_multiple_files.go
- rules/aip0191/java_multiple_files_test.go
- rules/aip0192/no_html.go
- rules/aip0233/aip0233.go
- rules/aip0234/aip0234.go
This cleans up our CI configuration slightly.
Importantly, it also adds `-v` to the unit tests. The original
rationale for touching this file is that there is a unit test that
is flaky (but only in CI) and I want more information about the
failure.
> [chore] CI refresh

- rules/aip0133/aip0133.go
- rules/aip0133/http_uri_parent.go
- rules/aip0133/http_uri_parent_test.go
The linter was providing a false positive for requiring
a parent field on Create methods.
> [fix] Fix Create parent false positive.

- docs/rules/0132/response-unknown-fields.md
> [fix] Fix permalink for 132/response-unknown-fields

- rules/internal/utils/extension.go
- rules/internal/utils/extension_test.go
AIP-123 rules using these are forthcoming.
> [feat] Add GetResource and GetResourceReference methods.

- rules/aip0191/java_multiple_files.go
- rules/aip0191/java_multiple_files_test.go
- rules/aip0191/java_outer_classname.go
- rules/aip0191/java_outer_classname_test.go
> [fix] Make Java annotation rules resilient against Google internal tool.

- docs/rules/0203/required.md
> Fixed issue #473

- rules/aip0126/unspecified.go
- rules/aip0126/unspecified_test.go
Resolve #466
- check if at least one enum with <name>_UNSPECIFIED
- check if <name>_UNSPECIFIED = 0
- added alias test case.
> [AIP-216] support alias

- docs/rules/0191/file-layout.md
> [fix] Correct file layout documentation.

- go.sum
Not sure why my result does not match Renovate's, but hopefully this sticks.
> [chore] go mod tidy

- docs/rules/0192/trademarked-names.md
- rules/aip0192/aip0192.go
- rules/aip0192/trademarked_names.go
- rules/aip0192/trademarked_names_test.go
Implements this AIP PR: googleapis/aip#420
~Do not merge until the AIP PR is merged.~ EDIT: It now is.
> [AIP-192] Add rule for trademarked names.

- rules/aip0191/java_outer_classname.go
- rules/aip0191/java_outer_classname_test.go
> [AIP-191] Enforce java_outer_classname.

- docs/rules/0140/uri.md
- rules/aip0140/aip0140.go
- rules/aip0140/uri.go
- rules/aip0140/uri_test.go
Do not merge until googleapis/aip#519 is merged.
> [AIP-140] Prohibit url in field names.

- docs/rules/0203/output-only.md
> [docs] Fix output-only docs.

- docs/rules/0140/numbers.md
- rules/aip0140/aip0140.go
- rules/aip0140/numbers.go
- rules/aip0140/numbers_test.go
Do not merge until googleapis/aip#528 is merged.
> [AIP-140] Prohibit starting any word with a number.

- rules/aip0191/csharp_namespace.go
- rules/aip0191/csharp_namespace_test.go
> [AIP-191] Handle point versions correctly in C#.

- docs/rules/0163/index.md
- docs/rules/0163/synonyms.md
- rules/aip0163/aip0163.go
- rules/aip0163/aip0163_test.go
- rules/aip0163/synonyms.go
- rules/aip0163/synonyms_test.go
- rules/rules.go
This is a common and easy-to-catch mistake.
> [AIP-163] Add rule for `dry_run` -> `validate_only`.

- .github/renovate.json5
This was a suggestion from @noahdietz awhile back, and it
makes sense.
> [chore] Update genproto once a month.

- rules/aip0231/response_resource_field.go
- rules/aip0231/response_resource_field_test.go
> fix: BatchGet rule now singularizes correctly.

- rules/aip0143/string_type.go
- rules/aip0143/string_type_test.go
> fix: Allow google.type.TimeZone for time zones.

- docs/rules/0191/java-outer-classname.md
> Docs: Fix rule title for AIP-191 java-outer-classname

- rules/aip0126/unspecified.go
- rules/aip0126/unspecified_test.go
> fix: Fix enums with words ending in numerals.

- rules/aip0133/request_unknown_fields.go
- rules/aip0134/request_unknown_fields.go
- rules/aip0135/request_unknown_fields.go
https://google.aip.dev/163 defines the `validate_only` field.
> Update placeholders for AIP-163

- docs/rules/0235/plural-method-name.md
- rules/aip0235/aip0235.go
- rules/aip0235/plural_method_name.go
- rules/aip0235/plural_method_name_test.go
Adapted from that of AIP-234 for #612.
> Add plural-method-name rule for AIP-235

- docs/rules/0235/http-uri-suffix.md
- rules/aip0235/http_uri_suffix.go
- rules/aip0235/http_uri_suffix_test.go
Adapted from that of AIP-234 for #612.
> feat: Add http-uri-suffix rule for AIP-235.

- rules/aip0231/aip0231.go
- rules/aip0231/http_uri_suffix.go
- rules/aip0231/http_uri_suffix_test.go
- rules/aip0233/aip0233.go
- rules/aip0233/http_uri_suffix.go
- rules/aip0233/http_uri_suffix_test.go
- rules/aip0234/aip0234.go
- rules/aip0234/http_uri_suffix.go
- rules/aip0234/http_uri_suffix_test.go
> fix: Permit batch methods on parent-less resources.

- .github/label-sync.yml
see: https://github.com/googleapis/repo-automation-bots/pull/979
> build: add config to turn off label-sync

- docs/rules/0235/request-parent-field.md
- rules/aip0235/aip0235.go
- rules/aip0235/request_parent_field.go
- rules/aip0235/request_parent_field_test.go
> Add request-parent-field rule for AIP 235

- docs/rules/0233/request-requests-behavior.md
- docs/rules/0234/request-requests-behavior.md
- docs/rules/0235/request-requests-behavior.md
- rules/aip0233/aip0233.go
- rules/aip0233/request_requests_behavior.go
- rules/aip0233/request_requests_behavior_test.go
- rules/aip0234/aip0234.go
- rules/aip0234/request_requests_behavior.go
- rules/aip0234/request_requests_behavior_test.go
- rules/aip0235/aip0235.go
- rules/aip0235/request_requests_behavior.go
- rules/aip0235/request_requests_behavior_test.go
> Add rules for batch-method requests field behavior

- docs/rules/0231/request-names-field.md
- docs/rules/0231/request-parent-field.md
- docs/rules/0231/request-parent-reference.md
- docs/rules/0233/request-parent-field.md
- docs/rules/0233/request-parent-reference.md
- docs/rules/0233/request-requests-field.md
- docs/rules/0234/request-parent-field.md
- docs/rules/0234/request-parent-reference.md
- docs/rules/0234/request-requests-field.md
- docs/rules/0235/request-names-behavior.md
- docs/rules/0235/request-names-field.md
- docs/rules/0235/request-parent-field.md
- docs/rules/0235/request-parent-reference.md
- rules/aip0231/aip0231.go
- rules/aip0231/request_parent_reference.go
- rules/aip0231/request_parent_reference_test.go
- rules/aip0233/aip0233.go
- rules/aip0233/request_parent_reference.go
- rules/aip0233/request_parent_reference_test.go
- rules/aip0234/aip0234.go
- rules/aip0234/request_parent_reference.go
- rules/aip0234/request_parent_reference_test.go
- rules/aip0235/aip0235.go
- rules/aip0235/request_parent_reference.go
- rules/aip0235/request_parent_reference_test.go
> Add rules for batch-method parent resource reference

- docs/rules/0158/response-repeated-first-field.md
Add "=disabled" or it doesn't work.
> Update the API-Linter 0158 page

- docs/rules/0231/request-unknown-fields.md
- docs/rules/0233/request-unknown-fields.md
- docs/rules/0234/request-unknown-fields.md
- docs/rules/0235/request-unknown-fields.md
- rules/aip0231/aip0231.go
- rules/aip0231/request_unknown_fields.go
- rules/aip0231/request_unknown_fields_test.go
- rules/aip0233/aip0233.go
- rules/aip0233/request_unknown_fields.go
- rules/aip0233/request_unknown_fields_test.go
- rules/aip0234/aip0234.go
- rules/aip0234/request_unknown_fields.go
- rules/aip0234/request_unknown_fields_test.go
- rules/aip0235/aip0235.go
- rules/aip0235/request_unknown_fields.go
- rules/aip0235/request_unknown_fields_test.go
> Add rules for unknown fields in batch requests

- go.mod
- go.sum
- rules/internal/utils/declarative_friendly.go
- rules/internal/utils/declarative_friendly_test.go
- rules/internal/utils/extension.go
This will be needed for upcoming declarative-friendly lint checks.
> feat: Add IsDeclarativeFriendly utility method.

- docs/rules/0235/response-resource-field.md
- rules/aip0235/aip0235.go
- rules/aip0235/response_resource_field.go
- rules/aip0235/response_resource_field_test.go
> Add rule for AIP-235 soft-delete response resource field

- docs/rules/0235/response-message-name.md
- rules/aip0235/aip0235.go
- rules/aip0235/response_message_name.go
- rules/aip0235/response_message_name_test.go
> Add rule for AIP-235 response message name

- rules/aip0203/aip0203.go
- rules/aip0203/optional.go
- rules/aip0203/optional_conflict.go
- rules/aip0203/required.go
This removes some false positive warnings.
> fix: Loosen warnings around REQUIRED and OPTIONAL.

- docs/rules/0203/required-and-optional.md
- locations/field_locations.go
- locations/field_locations_test.go
- rules/aip0203/aip0203.go
- rules/aip0203/required_and_optional.go
- rules/aip0203/required_and_optional_test.go
> feat: Add rule to prevent optional and required together.

- docs/rules/0148/human-names.md
- docs/rules/0148/index.md
- rules/aip0148/aip0148.go
- rules/aip0148/aip0148_test.go
- rules/aip0148/human_names.go
- rules/aip0148/human_names_test.go
- rules/rules.go
As opposed to `first_name` and `last_name`.
> feat: Add rule for `given_name` and `family_name`.

- docs/rules/0133/request-id-field.md
- docs/rules/0163/declarative-friendly-required.md
- rules/aip0133/aip0133.go
- rules/aip0133/request_id_field.go
- rules/aip0133/request_id_field_test.go
> feat: Add client-specified ID lint rule.

- docs/rules/0133/response-lro.md
- rules/aip0133/aip0133.go
- rules/aip0133/response_lro.go
- rules/aip0133/response_lro_test.go
> feat: Add LRO rule for Create methods (declarative-friendly).

- docs/rules/0135/response-lro.md
- rules/aip0135/aip0135.go
- rules/aip0135/response_lro.go
- rules/aip0135/response_lro_test.go
> feat: Add LRO rule for Delete methods (declarative-friendly).

- docs/rules/0135/response-message-name.md
- rules/aip0135/response_message_name.go
- rules/aip0135/response_message_name_test.go
- rules/internal/utils/declarative_friendly.go
> feat: Add declarative-friendly logic to the Delete response check.

- docs/rules/0128/index.md
- docs/rules/0128/resource-annotations-field.md
- rules/aip0128/aip0128.go
- rules/aip0128/resource_annotations_field.go
- rules/aip0128/resource_annotations_field_test.go
- rules/internal/utils/type_name.go
- rules/rules.go
> feat: Add rule for AIP-128 annotations field.

- docs/rules/0128/resource-reconciling-field.md
- rules/aip0128/aip0128.go
- rules/aip0128/resource_reconciling_field.go
- rules/aip0128/resource_reconciling_field_test.go
> feat: Add rule for AIP-128 reconciling field

- docs/rules/0164/declarative-friendly-required.md
- rules/aip0164/aip0164.go
- rules/aip0164/declarative_friendly_required.go
- rules/aip0164/declarative_friendly_required_test.go
> feat: Add rule to require Undelete methods for declarative-friendly resources

- docs/rules/0136/declarative-standard-methods-only.md
- rules/aip0136/aip0136.go
- rules/aip0136/declarative_standard_methods_only.go
- rules/aip0136/declarative_standard_methods_only_test.go
> feat: Declarative-friendly resources should avoid custom methods.

- docs/rules/0144/http-body.md
- docs/rules/0144/http-method.md
- docs/rules/0144/index.md
- docs/rules/0144/request-message-name.md
- rules/aip0144/aip0144.go
- rules/aip0144/aip0144_test.go
- rules/aip0144/http_body.go
- rules/aip0144/http_body_test.go
- rules/aip0144/http_method.go
- rules/aip0144/http_method_test.go
- rules/aip0144/request_message_name.go
- rules/aip0144/request_message_name_test.go
- rules/rules.go
> Add rules for AIP-144 HTTP method, HTTP body, request message name

- docs/rules/0165/response-message-name.md
- rules/aip0165/aip0165.go
- rules/aip0165/response_message_name.go
- rules/aip0165/response_message_name_test.go
> feat: Add rule for AIP-165 long-running response type

- docs/rules/0192/no-markdown-headings.md
- docs/rules/0192/only-leading-comments.md
- rules/aip0192/aip0192.go
- rules/aip0192/no_markdown_headings.go
- rules/aip0192/no_markdown_headings_test.go
> feat: Add rule prohibiting Markdown headings.

- docs/rules/0192/no-markdown-tables.md
- rules/aip0192/aip0192.go
- rules/aip0192/no_markdown_tables.go
- rules/aip0192/no_markdown_tables_test.go
> feat: Add rule prohibiting Markdown tables.

- docs/rules/0162/commit-http-uri-suffix.md
- rules/aip0162/aip0162.go
- rules/aip0162/commit_http_uri_suffix.go
- rules/aip0162/commit_http_uri_suffix_test.go
> feat: Add rule for AIP-162 Commit HTTP URI suffix

- docs/rules/0162/commit-http-body.md
- docs/rules/0162/commit-http-method.md
- rules/aip0162/aip0162.go
- rules/aip0162/commit_http_body.go
- rules/aip0162/commit_http_body_test.go
- rules/aip0162/commit_http_method.go
- rules/aip0162/commit_http_method_test.go
> feat: Add rules for AIP-162 Commit HTTP body and method

- docs/rules/0162/commit-request-message-name.md
- rules/aip0162/aip0162.go
- rules/aip0162/commit_request_message_name.go
- rules/aip0162/commit_request_message_name_test.go
> feat: Add rule for AIP-162 Commit request message name

- docs/rules/0162/commit-response-message-name.md
- rules/aip0162/aip0162.go
- rules/aip0162/commit_response_message_name.go
- rules/aip0162/commit_response_message_name_test.go
> feat: Add rule for AIP-162 Commit response message name

- docs/rules/0162/rollback-http-uri-suffix.md
- rules/aip0162/aip0162.go
- rules/aip0162/rollback_http_uri_suffix.go
- rules/aip0162/rollback_http_uri_suffix_test.go
> feat: Add rule for AIP-162 Rollback HTTP URI suffix

- docs/rules/0162/rollback-http-body.md
- docs/rules/0162/rollback-http-method.md
- rules/aip0162/aip0162.go
- rules/aip0162/rollback_http_body.go
- rules/aip0162/rollback_http_body_test.go
- rules/aip0162/rollback_http_method.go
- rules/aip0162/rollback_http_method_test.go
> feat: Add rules for AIP-162 Rollback HTTP method and body

- rules/aip0131/request_name_field.go
- rules/aip0132/request_parent_field.go
- rules/aip0133/request_parent_field.go
- rules/aip0135/request_name_field.go
- rules/aip0152/request_name_field.go
- rules/aip0158/request_page_token_field.go
- rules/aip0158/response_next_page_token_field.go
- rules/aip0162/commit_request_name_field.go
- rules/aip0162/tag_revision_request_name_field.go
- rules/aip0162/tag_revision_request_tag_field.go
- rules/aip0164/request_name_field.go
- rules/aip0165/request_filter_field.go
- rules/aip0165/request_parent_field.go
- rules/aip0231/request_parent_field.go
- rules/aip0233/request_parent_field.go
- rules/aip0234/request_parent_field.go
- rules/aip0235/request_parent_field.go
- rules/internal/utils/common_lints.go
- rules/internal/utils/common_lints_test.go
> refactor: Add and more widely use helpers for field presence and singular-string type

- docs/rules/0162/rollback-request-message-name.md
- docs/rules/0162/rollback-response-message-name.md
- rules/aip0162/aip0162.go
- rules/aip0162/rollback_request_message_name.go
- rules/aip0162/rollback_request_message_name_test.go
- rules/aip0162/rollback_response_message_name.go
- rules/aip0162/rollback_response_message_name_test.go
> feat: Add rules for AIP-162 Rollback request and response message name

- docs/rules/0162/rollback-request-name-behavior.md
- docs/rules/0162/rollback-request-name-field.md
- docs/rules/0162/rollback-request-name-reference.md
- rules/aip0162/aip0162.go
- rules/aip0162/rollback_request_name_behavior.go
- rules/aip0162/rollback_request_name_behavior_test.go
- rules/aip0162/rollback_request_name_field.go
- rules/aip0162/rollback_request_name_field_test.go
- rules/aip0162/rollback_request_name_reference.go
- rules/aip0162/rollback_request_name_reference_test.go
> feat: Add rules for AIP-162 Rollback request name field, behavior, and resource reference

- docs/rules/0162/rollback-request-revision-id-behavior.md
- docs/rules/0162/rollback-request-revision-id-field.md
- rules/aip0162/aip0162.go
- rules/aip0162/rollback_request_revision_id_behavior.go
- rules/aip0162/rollback_request_revision_id_behavior_test.go
- rules/aip0162/rollback_request_revision_id_field.go
- rules/aip0162/rollback_request_revision_id_field_test.go
> feat: Add rules for AIP-162 Rollback request revision_id field and behavior

- docs/rules/0162/delete-revision-http-uri-suffix.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_http_uri_suffix.go
- rules/aip0162/delete_revision_http_uri_suffix_test.go
> feat: Add rule for AIP-162 Delete Revision HTTP URI suffix

- docs/rules/0162/delete-revision-request-message-name.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_request_message_name.go
- rules/aip0162/delete_revision_request_message_name_test.go
> feat: Add rule for AIP-162 Delete Revision request message name

- docs/rules/0132/request-parent-valid-reference.md
- rules/aip0132/aip0132.go
- rules/aip0132/request_parent_valid_reference.go
- rules/aip0132/request_parent_valid_reference_test.go
This lints List*Request parent resource_reference annotations to check it does not reference the resource being listed.
> feat: validate list parent resource_reference

- docs/rules/0162/delete-revision-request-name-field.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_request_name_field.go
- rules/aip0162/delete_revision_request_name_field_test.go
> feat:Add rule for AIP-162 Delete Revision request name field

- docs/rules/0162/delete-revision-request-name-behavior.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_request_name_behavior.go
- rules/aip0162/delete_revision_request_name_behavior_test.go
> feat: Add rule for AIP-162 Delete Revision request name field behavior

- docs/rules/0162/delete-revision-request-name-reference.md
- rules/aip0162/aip0162.go
- rules/aip0162/delete_revision_request_name_reference.go
- rules/aip0162/delete_revision_request_name_reference_test.go
> feat: Add rule for AIP-162 Delete Revision request name field resource reference

- docs/rules/0162/list-revisions-http-body.md
- rules/aip0162/aip0162.go
- rules/aip0162/list_revisions_http_body.go
- rules/aip0162/list_revisions_http_body_test.go
> feat: Add rule for AIP-162 HTTP body

- docs/rules/0162/list-revisions-http-uri-suffix.md
- rules/aip0162/aip0162.go
- rules/aip0162/list_revisions_http_uri_suffix.go
- rules/aip0162/list_revisions_http_uri_suffix_test.go
> feat: Add rule for AIP-162 List Revisions HTTP URI suffix

- docs/rules/0162/list-revisions-request-name-field.md
- rules/aip0162/aip0162.go
- rules/aip0162/list_revisions_request_name_field.go
- rules/aip0162/list_revisions_request_name_field_test.go
> feat: Add rule for AIP-162 List Revisions request name field

- docs/rules/0123/duplicate-resource.md
- locations/file_locations.go
- rules/aip0123/aip0123.go
- rules/aip0123/duplicate_resource.go
- rules/aip0123/duplicate_resource_test.go
> feat: Add rule to prevent duplicate resource definitions

- rules/aip0235/request_parent_field.go
- rules/aip0235/request_parent_field_test.go
- rules/internal/utils/string_pluralize.go
> fix: Fix handling of top-level resources in AIP-235 request-parent-field rule

- docs/rules/0123/resource-reference-type.md
- rules/aip0123/aip0123.go
- rules/aip0123/resource_reference_type.go
- rules/aip0123/resource_reference_type_test.go
> feat: AIP-123 – Complain if resource references are not strings.

- rules/aip0122/camel_case_uris.go
- rules/aip0127/http_annotation.go
- rules/aip0131/http_uri_name.go
- rules/aip0133/http_body.go
- rules/aip0133/http_uri_parent.go
- rules/aip0134/http_body.go
- rules/aip0134/http_uri_name.go
- rules/aip0135/http_uri_name.go
- rules/aip0136/http_body.go
- rules/aip0136/http_method.go
- rules/aip0136/http_name_variable.go
- rules/aip0136/http_parent_variable.go
- rules/aip0152/http_uri_suffix.go
- rules/aip0162/commit_http_uri_suffix.go
- rules/aip0162/delete_revision_http_uri_suffix.go
- rules/aip0162/list_revisions_http_uri_suffix.go
- rules/aip0162/rollback_http_uri_suffix.go
- rules/aip0162/tag_revision_http_uri_suffix.go
- rules/aip0164/http_uri_suffix.go
- rules/aip0165/http_uri_suffix.go
- rules/aip0231/http_uri_suffix.go
- rules/aip0233/http_uri_suffix.go
- rules/aip0234/http_uri_suffix.go
- rules/aip0235/http_uri_suffix.go
- rules/internal/utils/common_lints.go
This gives more precise information than the entire method.
> fix: Use HTTP rule instead of method as location for relevant problems

- rules/aip0132/request_field_types.go
- rules/aip0132/request_field_types_test.go
- rules/aip0133/request_id_field.go
- rules/aip0133/request_id_field_test.go
- rules/aip0134/request_allow_missing_field.go
- rules/aip0134/request_allow_missing_field_test.go
- rules/aip0134/request_mask_field.go
- rules/aip0134/request_mask_field_test.go
- rules/aip0154/field_type.go
- rules/aip0154/field_type_test.go
- rules/aip0158/request_page_size_field.go
- rules/aip0163/declarative_friendly_required.go
- rules/aip0163/declarative_friendly_required_test.go
> fix: Check field cardinality for AIP-132, AIP-133, AIP-134, AIP-154, AIP-158, AIP-163

- docs/rules/0164/resource-expire-time-field.md
- rules/aip0164/aip0164.go
- rules/aip0164/resource_expire_time_field.go
- rules/aip0164/resource_expire_time_field_test.go
> feat: Require expire_time field in resources supporting soft-delete

- go.sum
> chore: Run `go mod tidy` so build succeeds at HEAD

- rules/aip0124/reference_same_package.go
- rules/aip0124/valid_reference.go
- rules/aip0151/lro_response_reachable.go
- rules/aip0151/lro_response_reachable_test.go
- rules/internal/utils/find.go
> fix: Consider messages in transitive dependencies reachable for AIP-151

- docs/rules/0128/resource-reconciling-behavior.md
- rules/aip0128/resource_annotations_field.go
- rules/aip0128/resource_reconciling_behavior.go
- rules/aip0128/resource_reconciling_behavior_test.go
- rules/aip0128/resource_reconciling_field.go
- rules/internal/utils/common_lints.go
> feat: Require declarative-friendly reconciling fields to be output-only

- docs/rules/0148/field-behavior.md
- rules/aip0148/field_behavior.go
- rules/aip0148/field_behavior_test.go
> feat: Require standard create_time, delete_time, uid, and update_time fields to be output only

- docs/rules/0132/request-field-types.md
- docs/rules/0132/request-unknown-fields.md
- rules/aip0132/request_field_types.go
- rules/aip0132/request_field_types_test.go
- rules/internal/utils/common_lints.go
> feat: Require show_deleted List request field to be a singular bool

- rules/aip0134/request_allow_missing_field.go
- rules/aip0134/request_allow_missing_field_test.go
- rules/aip0148/declarative_friendly_fields.go
- rules/internal/utils/extension.go
> fix: Do not require allow_missing Update request field for singleton resources

- docs/rules/0132/request-show-deleted-required.md
- rules/aip0132/aip0132.go
- rules/aip0132/request_show_deleted_required.go
- rules/aip0132/request_show_deleted_required_test.go
> feat: Require show_deleted List request field for resources supporting soft delete

- docs/rules/0132/request-unknown-fields.md
- rules/aip0132/request_unknown_fields.go
- rules/aip0132/request_unknown_fields_test.go
Corresponds to https://github.com/aip-dev/google.aip.dev/pull/754.
> feat: Permit `skip` in List requests.

- docs/rules/0133/http-uri-parent.md
- rules/aip0133/http_uri_parent.go
- rules/aip0133/http_uri_parent_test.go
- rules/internal/utils/common_lints.go
> feat: Validate that parent is only variable for AIP-133

- rules/aip0191/proto_package.go
- rules/aip0191/proto_package_test.go
> fix(AIP-191): restrict proto pkg match

- docs/rules/0234/request-unknown-fields.md
- rules/aip0234/request_unknown_fields.go
- rules/aip0234/request_unknown_fields_test.go
> fix: Allow AIP-234 Batch Update requests to hoist allow_missing field

- docs/rules/0157/index.md
- docs/rules/0157/request-read-mask-field.md
- rules/aip0157/aip0157.go
- rules/aip0157/request_read_mask_field.go
- rules/aip0157/request_read_mask_field_test.go
- rules/internal/utils/common_lints.go
- rules/rules.go
> feat: Add rule to check type of AIP-157 request read_mask fields

- docs/rules/0158/request-skip-field.md
- rules/aip0158/aip0158.go
- rules/aip0158/request_skip_field.go
- rules/aip0158/request_skip_field_test.go
Corresponds to #845 and aip-dev/google.aip.dev#754.
> feat: Add rule to check type of AIP-158 paginated request skip field

- locations/file_locations.go
- locations/file_locations_test.go
Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>
> feat: add location function for imports

- locations/file_locations.go
- locations/file_locations_test.go
Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>
> chore: add location helper for `cc_enable_arenas` file option

- lint/rule.go
This function might be helpful for example in rule implementation.
Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>
> chore: export GetAllMessages function.

- docs/rules/0133/http-uri-resource.md
- rules/aip0133/aip0133.go
- rules/aip0133/http_uri_resource.go
- rules/aip0133/http_uri_resource_test.go
> feat: Validate that resource maps to URI path for AIP-133 

- rules/aip0158/request_page_size_field.go
- rules/aip0158/request_page_size_field_test.go
- rules/aip0158/request_page_token_field.go
- rules/aip0158/request_page_token_field_test.go
- rules/internal/utils/common_lints.go
- rules/internal/utils/common_lints_test.go
> feat(AIP-158): standard fields should not be in a oneof

- cmd/api-linter/integration_test.go
- cmd/api-linter/main.go
- cmd/api-linter/rules.go
- cmd/api-linter/summary_test.go
These preexisted my other PR, but were easy enough to fix.
> fix(cmd/api-linter): address lint errors

- rules/aip0192/has_comments_test.go
I'm investigating issues with signaling of missing comments when the only comment is an internal one. The tests didn't cover this case, so I'm adding more.
This rule applies to all elements, and probably doesn't need specific tests for each possible element, but I broke up the existing test into two different ones, so that I could test message and field level comments (where we are seeing issues).
> chore(AIP-192): add tests for has_comments

- docs/rules/0127/http-template-pattern.md
- rules/aip0127/aip0127.go
- rules/aip0127/http_template_pattern.go
- rules/aip0127/http_template_pattern_test.go
- rules/internal/utils/http.go
> feat: Validate that HTTP variable templates match resource pattern definitions (AIP-127)

- rules/aip0216/value_synonyms.go
- rules/aip0216/value_synonyms_test.go
> feat(AIP-216): enforce CANCELING as CANCELLING

- rules/aip0122/name_suffix.go
> fix(AIP-122): allow cmek_key_name

- docs/rules/0146/any.md
[Internal feedback](http://b/286263871) discovered this doc page was incorrectly linked.
> fix(AIP-146): fix rule doc link

- rules/aip0142/time_field_names.go
- rules/aip0203/field_behavior_required.go
- rules/aip0203/field_behavior_required_test.go
Some messages can be recursive, which lead to stackoverflows.
> fix(AIP-203): handle recursive field behavior check

- .github/release-please.yml
Also explicitly identify the changelog file (local testing resulted in a changes.md being made instead)
> fix(ci): rename release-please app file

- docs/rules/0121/resource-must-support-get.md
- docs/rules/0121/resource-must-support-list.md
- rules/aip0121/aip0121.go
- rules/aip0121/resource_must_support_get.go
- rules/aip0121/resource_must_support_list.go
- rules/aip0121/resource_must_support_list_test.go
> feat(AIP-121): enforce list requirement

- docs/rules/0156/forbidden-methods.md
- rules/aip0156/forbidden_methods.go
- rules/aip0156/forbidden_methods_test.go
Allow Singleton resources to have Standard List as per https://github.com/aip-dev/google.aip.dev/pull/1195
> feat(AIP-156): allow singleton list

- docs/rules/0121/no-mutable-cycles.md
Previous title was for resource-must-support-get
Use the rule summary as the new page title.
> chore(AIP-121): fix title for no-mutable-cycles doc

- docs/rules/0142/time-field-names.md
- rules/aip0142/time_field_names.go
Closes https://github.com/googleapis/api-linter/issues/1131.
> feat(AIP-142): warn on creation_time

- docs/rules/0131/request-unknown-fields.md
- docs/rules/0132/request-unknown-fields.md
- rules/aip0131/request_unknown_fields.go
- rules/aip0131/request_unknown_fields_test.go
- rules/aip0132/request_unknown_fields.go
- rules/aip0132/request_unknown_fields_test.go
Closes https://github.com/googleapis/api-linter/issues/1311.
> feat: allow `request_id` for standard Get and List

- cmd/api-linter/integration_test.go
Ports an internal change meant to prepare for upgrading jhump/protoreflect ahead of [protobuf editions](https://protobuf.dev/editions/overview/) support.
> fix: tweak cli integration test

- docs/rules/0140/reserved-words.md
Just fixes a very minor typo on this page.
> fix: docs typo

- rules/aip0136/http_body.go
- rules/aip0136/http_body_test.go
- rules/internal/testutils/parse.go
Updates #1207
Iternal bug to port this change to OSS implementation: http://b/353985049
> fix(AIP-136): allow google.api.HttpBody as body field

- docs/rules/0148/uid-format.md
Continuing the contribution in #1280 from @achew22.
> docs(AIP-148): linkify UUID4 format in rule
